Testando BGE-M3

In [57]:
from FlagEmbedding import BGEM3FlagModel
from FlagEmbedding import FlagReranker
from qdrant_client.models import Prefetch, FusionQuery, Fusion, models
from qdrant_client import QdrantClient, models
from qdrant_client.models import Distance, VectorParams, SparseVectorParams
from qdrant_client.models import PointStruct, SparseVector
import uuid
import pprint
from bson import ObjectId
import json
import io
import os
import boto3
import pandas as pd

Conectar banco MinIO

In [2]:
def get_parquet_file(bucket, file_name):
    endpoint = os.getenv("MINIO_ENDPOINT", "http://localhost:9000")

    s3 = boto3.client(
        "s3",
        endpoint_url=endpoint,
        aws_access_key_id=os.getenv("MINIO_ACCESS_KEY"),
        aws_secret_access_key=os.getenv("MINIO_SECRET_KEY"),
    )

    response = s3.get_object(
        Bucket=bucket,
        Key=file_name
    )

    return pd.read_parquet(
        io.BytesIO(response["Body"].read())
    )

Obter dados do env

In [ ]:
from dotenv import load_dotenv

load_dotenv()

True

In [4]:
professores_dados = get_parquet_file("gold", "professores_unificados.parquet")

In [5]:
disciplinas_dados = get_parquet_file("silver", "componentes_curriculares.parquet")

In [6]:
ics_dados = get_parquet_file("silver", "trabalhos_ic_periodicos.parquet")

In [7]:
print(professores_dados.columns)

Index(['nome', 'idLattes', 'siape', 'resumo', 'formacaoAcademicaProfissional',
       'areasInteresse', 'competencias', 'producoes', 'producaoDocenteSigaa',
       'projetos', 'orientacoes', 'disciplinasSigaa',
       'trabalhosIniciacaoCientifica'],
      dtype='object')

In [8]:
print(disciplinas_dados.columns)

Index(['idSigaa', 'codigo', 'nome', 'cargaHoraria', 'ementa'], dtype='object')

In [9]:
print(ics_dados.columns)

Index(['id', 'titulo', 'autores', 'resumo', 'palavrasChaves', 'ano'], dtype='object')

In [10]:
ics_dados = ics_dados.to_dict("records")

In [11]:
professores_dados = professores_dados.to_dict("records")

In [181]:
disciplinas_dados = disciplinas_dados.to_dict("records")

Criação do perfil do professor

In [21]:
def montar_texto_producao(producao):
    partes = []

    if producao.get("titulo"):
        partes.append(f"Título: {producao['titulo']}")

    if producao.get("resumo"):
        partes.append(f"Resumo: {producao['resumo']}")

    if producao.get("palavrasChaves").any():
        partes.append(
            f"Palavras-chave: {', '.join(producao['palavrasChaves'])}"
        )

    return "\n".join(partes)

In [13]:
def montar_texto_competencias(competencias):
    partes = []

    areas = competencias.get("areas")

    if areas is not None and len(areas) > 0:
        textos_areas = []

        for area in areas:
            campos = []

            if area.get("grande_area"):
                campos.append(f"Grande área: {area['grande_area']}")

            if area.get("area"):
                campos.append(f"Área: {area['area']}")

            if area.get("subarea"):
                campos.append(f"Subárea: {area['subarea']}")

            if area.get("especialidade"):
                campos.append(f"Especialidade: {area['especialidade']}")

            if campos:
                textos_areas.append(". ".join(campos))

        if textos_areas:
            partes.append(
                "Áreas de conhecimento:\n" +
                "\n".join(textos_areas)
            )

    linhas = competencias.get("linhas_pesquisa")

    if linhas is not None and len(linhas) > 0:
        partes.append(
            "Linhas de pesquisa: " + ", ".join(linhas)
        )

    palavras_chave = competencias.get("palavras_chave")

    if palavras_chave is not None and len(palavras_chave) > 0:
        partes.append(
            "Palavras-chave: " + ", ".join(palavras_chave)
        )

    return "\n\n".join(partes)

In [14]:
def montar_texto_perfil_professor(perfil):

    partes = []
    
    if perfil.get("resumo"):
        partes.append(f"Resumo: {perfil['resumo']}")
    
    if perfil.get("formacaoAcademicaProfissional"):
        partes.append(
            f"Formação Profissional Acadêmica: "
            f"{perfil['formacaoAcademicaProfissional']}"
        )

    if perfil.get("areasInteresse").any():
        partes.append(
            f"Áreas de Interesse: "
            f"{', '.join(perfil['areasInteresse'])}"
        )    
    if perfil.get("competencias"):
        competencias_texto = montar_texto_competencias(
            perfil["competencias"]
        )
        if competencias_texto:
            partes.append(competencias_texto)
    
    return "\n".join(partes)

In [193]:
def montar_texto_disciplina(disciplina):
    partes = []

    if disciplina.get("nome"):
        partes.append(f"Nome: {disciplina['nome']}")

    if disciplina.get("ementa"):
        partes.append(f"Ementa: {disciplina['ementa']}")

    return "\n".join(partes)

BGE-M3

In [15]:
# bge-m3 vai ficar na mémoria da nossa aplicação
def carregar_bgeM3():
    return BGEM3FlagModel('BAAI/bge-m3', use_fp16=True)

def rodar_bgeM3(modelo, texto):
    embedding = {}
    resultado = modelo.encode(
        texto,
        return_dense=True, 
        return_sparse=True
    )

    embedding = {
        "dense": resultado["dense_vecs"],
        "sparse": resultado["lexical_weights"]
    }

    return embedding

def obter_denso(perfis_transformados):
    return perfis_transformados['dense_vecs']

In [16]:
modelo = carregar_bgeM3()

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 30 files:   0%|          | 0/30 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

Criação dos Hash dos textos de Embedding

In [18]:
def gerar_hash(componentes):   
    json_normalizado = json.dumps(
        componentes,
        sort_keys=True,
        ensure_ascii=False,
        separators=(",", ":")
    )
    return hashlib.sha256(transformar_bytes(json_normalizado)).hexdigest()

In [17]:
import hashlib

def transformar_bytes(texto : str) -> bytes:
    t = texto
    return t.encode("utf-8")

Componentes (por enquanto) considerados para a busca :
- Perfil professor (Resumo, Formação Acadêmica Profissional, Áreas de interesse, Competências)
- Iniciação Científica
- Disciplinas

Criação do perfil dos conteúdos dos componentes

In [ ]:
def criar_perfils_trabalhos(trabalhos) -> list[dict]:
    trabalhos_texto = []
    for trabalho in trabalhos:
        texto_embedding = montar_texto_producao(trabalho)
        trabalho_transformado = {
            "id" : trabalho['id'], 
            "hash" : gerar_hash(texto_embedding),
            "texto_embedding": texto_embedding,
            "metadata" : {
               "titulo": trabalho['titulo'],
               "ano" : int(trabalho['ano']),
               "tipo": trabalho.get("tipo")
            }
        }
        trabalhos_texto.append(trabalho_transformado)
        
    return trabalhos_texto

In [22]:
ics_perfis_busca = criar_perfils_trabalhos(ics_dados)

In [24]:
ics_valores_denso_lexical= {}  
for ic in ics_perfis_busca:
        
    texto_transformado = rodar_bgeM3(modelo,ic.get("texto_embedding"))

    ics_valores_denso_lexical[ic["id"]] = texto_transformado

In [26]:
ics_valores_denso_lexical['9b3189cbc1da']

{'dense': array([-0.04400245,  0.02993284, -0.00196428, ..., -0.02217614,
        -0.02278105, -0.0018368 ], shape=(1024,), dtype=float32),
 'sparse': defaultdict(int,
             {'211025': np.float32(0.10696598),
              '122461': np.float32(0.10371503),
              '866': np.float32(0.13957539),
              '124661': np.float32(0.14100933),
              '241': np.float32(0.06076681),
              '55991': np.float32(0.13232352),
              '7146': np.float32(0.10805798),
              '276': np.float32(0.08453494),
              '43351': np.float32(0.12482357),
              '52069': np.float32(0.043306984),
              '117772': np.float32(0.07535648),
              '62958': np.float32(0.122521356),
              '8575': np.float32(0.12503597),
              '122359': np.float32(0.16912784),
              '36321': np.float32(0.09868437),
              '89944': np.float32(0.08621602),
              '6': np.float32(0.011776261),
              '49877': np.float32(0.16234216),
              '304': np.float32(0.21110846),
              '61293': np.float32(0.12748632),
              '22628': np.float32(0.18066396),
              '13197': np.float32(0.048300177),
              '46736': np.float32(0.008254811),
              '36': np.float32(0.00044704974),
              '36388': np.float32(0.0050315484),
              '352': np.float32(0.054317802),
              '15286': np.float32(0.026733056),
              '1156': np.float32(0.0021592453),
              '27725': np.float32(0.055161722),
              '923': np.float32(0.11873271),
              '19655': np.float32(0.13676521),
              '14019': np.float32(0.1740052),
              '40226': np.float32(0.26182866),
              '1140': np.float32(0.024310049),
              '19492': np.float32(0.1551908),
              '7968': np.float32(0.039754063),
              '34939': np.float32(0.21993896),
              '7': np.float32(0.0018590391),
              '223338': np.float32(0.1811555),
              '375': np.float32(0.070602976),
              '143027': np.float32(0.24078605),
              '100777': np.float32(0.16743746),
              '154678': np.float32(0.15939927),
              '41': np.float32(0.019286111),
              '14041': np.float32(0.007284157),
              '56303': np.float32(0.087379195),
              '1124': np.float32(0.0012663193),
              '1846': np.float32(0.14097925),
              '137077': np.float32(0.033315226),
              '22252': np.float32(0.018995542),
              '8': np.float32(0.1535566),
              '3647': np.float32(0.05809471),
              '362': np.float32(0.0018172637),
              '8582': np.float32(0.02491824),
              '655': np.float32(0.0015344992),
              '227995': np.float32(0.15616551),
              '7275': np.float32(0.16037905),
              '87926': np.float32(0.21735717),
              '4': np.float32(0.0030120648),
              '237': np.float32(0.00025242567),
              '5289': np.float32(0.034465507),
              '37534': np.float32(0.0263955),
              '14692': np.float32(0.0014969893),
              '110': np.float32(0.00036665052),
              '40': np.float32(0.00074192137),
              '107832': np.float32(0.012712061),
              '10': np.float32(0.0012924299),
              '222418': np.float32(0.13531956),
              '2244': np.float32(0.15096079),
              '22': np.float32(0.083081156),
              '3798': np.float32(0.16838881),
              '282': np.float32(0.15529802),
              '52452': np.float32(0.12258428),
              '4596': np.float32(0.0011932142),
              '174005': np.float32(0.043661006),
              '7098': np.float32(0.10657629),
              '381': np.float32(0.0013211444),
              '170919': np.float32(0.12494741),
              '90': np.float32(0.0022111088),
              '22077': np.float32(0.0012834482),
              '22824': np.float32(0.11897311),
              '123457': np.float32(0.0041766167),
              '5388': np.float32(0.030395769),
              '6336': np.float32(0.032931395),
              '5059': np.float32(0.017024659),
              '54241': np.float32(0.07916302),
              '68671': np.float32(0.14183709),
              '56231': np.float32(0.16324428),
              '3175': np.float32(0.0019947663),
              '196': np.float32(0.002703257),
              '15946': np.float32(0.004306115),
              '66749': np.float32(0.13321629),
              '11406': np.float32(0.1044197),
              '3448': np.float32(0.0013703108),
              '7617': np.float32(0.046573784),
              '23727': np.float32(0.0019135177),
              '43111': np.float32(0.11332668),
              '73544': np.float32(0.0041695386),
              '3163': np.float32(0.000321351),
              '587': np.float32(0.03817426),
              '7290': np.float32(0.0033033118),
              '226835': np.float32(0.11343464),
              '393': np.float32(0.015122779),
              '64004': np.float32(0.076033026),
              '4341': np.float32(0.012113482),
              '121': np.float32(0.011143312),
              '21385': np.float32(0.096214876),
              '43025': np.float32(0.09654918),
              '12983': np.float32(0.0817976),
              '6497': np.float32(0.002047535),
              '95523': np.float32(0.112532616),
              '13773': np.float32(0.06710263),
              '3332': np.float32(0.020557627),
              '42118': np.float32(0.06168148),
              '46188': np.float32(0.095047876),
              '216342': np.float32(0.07931094),
              '9': np.float32(0.0006057918),
              '1436': np.float32(0.08705347),
              '272': np.float32(0.0015182123),
              '357': np.float32(0.064546935),
              '24018': np.float32(0.08525601),
              '14': np.float32(0.043148123),
              '72394': np.float32(0.016983204),
              '144814': np.float32(0.22631265),
              '8647': np.float32(0.15932912),
              '13': np.float32(0.00087383017),
              '5346': np.float32(0.14869593),
              '31': np.float32(0.098003365)})}

In [30]:
def criar_perfils_professor(professores) -> list[dict]:
    perfis_texto = []
    for professor in professores:
        texto_embedding = montar_texto_perfil_professor(professor)
        professor_transformado = {
            "id" : professor['siape'], 
            "hash" : gerar_hash(texto_embedding),
            "texto_embedding": texto_embedding,
            "metadata" : {
               "nome": professor['nome'],
            }
        }
        perfis_texto.append(professor_transformado)

    return perfis_texto

In [31]:
professores_busca_perfis = criar_perfils_professor(professores_dados)

In [32]:
professores_busca_perfis

[{'id': '2234207',
  'hash': 'b5e1a2c4f3aba88a43fdeea157761b94dc1ae1c190371aee708d9f87d8ce4f2a',
  'texto_embedding': 'Resumo: Possui graduação em Engenharia Elétrica pela Universidade Federal de Itajubá (2010), mestrado e doutorado em Engenharia de Produção pela Universidade Federal de Itajubá (2015/2020). É especialista em Engenharia Clínica, trabalhou na área por 4 anos, com nos seguintes temas: inventário, seis sigma, interferências eletromagnéticas, equipamentos médicos, usabilidade e engenharia de fatores humanos. Também possui experiência na área de Engenharia de Produção em indústria de manufatura intensiva, na área de qualidade melhorias, com aplicação de Kaizens e projetos Seis Sigma. É professora da UNIFEI nas áreas de Eletrônica Analógica, Instrumentação Biomédica, Metodologia Científica e Usabilidade. É pesquisadora no programa Desenvolvimento Sociedade e Tecnologias e no Laboratório de Usabilidade e Fatores Humanos da UNIFEI\nFormação Profissional Acadêmica: Doutorado\nÁreas de Interesse: Usabilidade, Equipamentos Médicos, Engenharia Biomédica\nÁreas de conhecimento:\nGrande área: Engenharias. Área: Engenharia de Produção. Subárea: Seis Sigma\nGrande área: Engenharias. Área: Engenharia de Produção. Subárea: Qualidade\nGrande área: Engenharias. Área: Engenharia Biomédica. Subárea: Engenharia Clínica\nGrande área: Engenharias. Área: Engenharia Biomédica. Subárea: Usabilidade\nGrande área: Engenharias. Área: Engenharia Biomédica\n\nLinhas de pesquisa: Engenharia Biomédica, Usabilidade, Instrumentação Biomédica, Usabilidade, Desenvolvimento de Produto, Fatores Humanos, Ergonomia\n\nPalavras-chave: Usabilidade, Dispositivo Médico, Desenvolvimento de Produto, Regulamentação, Engenharia de Fatores Humanos, Equipamentos Médicos',
  'metadata': {'nome': 'ANA PAULA SIQUEIRA SILVA DE ALMEIDA'}},
 {'id': '1310498',
  'hash': '3446a828357f3d9b85615619975f89b9eed923c73e08d0c48f187adde16ce94a',
  'texto_embedding': 'Resumo: Possui graduação em Engenharia Elétrica pela Universidade Federal de Itajubá (1994), mestrado em Engenharia Elétrica pela Universidade Federal de Itajubá (1999) e doutorado em Engenharia Elétrica pela Universidade Federal de Itajubá (2022). Atualmente é professor associado ii na Universidade Federal de Itajubá. Tem experiência na área de Engenharia Elétrica, com ênfase em Processamento Digital de Sinais Elétricos e Programação Orientada a Objetos, Desenvolvimento de Sistemas Embarcados, atuando principalmente nos seguintes temas: deconvolução, sinais biomédicos, sinais ultrassônicos, SSA, SVD, rede CAN e protocolo CANopen\nFormação Profissional Acadêmica: Possui graduação em Engenharia Elétrica pela Universidade Federal de Itajubá (1994), mestrado em Engenharia Elétrica pela Universidade Federal de Itajubá (1999) e doutorado em Engenharia Elétrica pela Universidade Federal de Itajubá (2022). Atualmente é professor associado ii na Universidade Federal de Itajubá. Tem experiência na área de Engenharia Elétrica, com ênfase em Processamento Digital de Sinais Elétricos e Programação Orientada a Objetos, atuando principalmente nos seguintes temas: deconvolução, sinais biomédicos, sinais ultrassônicos, SSA, SVD.\nÁreas de Interesse: Linguagens de Programação e Processamento Digital de Sinais\nÁreas de conhecimento:\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Eletrônica Industrial, Sistemas e Controles Eletrônicos. Especialidade: Processamento Digital de Sinais Elétricos\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Metodologia e Técnicas da Computação. Especialidade: Linguagens de Programação\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Metodologia e Técnicas da Computação. Especialidade: Engenharia de Software\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: ENGENHARIA DE COMPUTAÇÃO\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Teoria da Computação. Especialidade: Análise de Algoritmos e Complexidade de Computação\n\nLinhas de pesquisa: Pesquisa e desenvolvimento sobre sistema Digital de Mapemento Cerebral e Eletroencefalograma, Processamento digital de sinais\n\nPalavras-chave: Deconvolution, Singular Spectral Analysis, Blind Source Separation, Independent Component Analysis, Filtro de Kalman, Eletroencefalograma, EEG, AR Model, Orientação a Objetos',
  'metadata': {'nome': 'ANDRE BERNARDI'}},
 {'id': '3443612',
  'hash': '63e0164ebccf43efe84056eca183e28aa59fa096e0b117f1610d446fc47b8f60',
  'texto_embedding': 'Resumo: Possui Doutorado em Engenharia de Dados e Conhecimento no Programa de Engenharia de Sistemas e Computação (PESC) - COPPE / UFRJ (2024), mestrado em Engenharia de Dados e Conhecimento no Programa de Engenharia de Sistemas e Computação (PESC) - COPPE / UFRJ (2018) e graduação em Sistemas de Informação pela Universidade Federal de Itajubá (2015). Atuou como professora nos cursos de Sistemas de Informação e Tecnologia em Análise e Desenvolvimento de Sistemas no Centro Universitário de Itajubá (Fepi). Durante a graduação foi membro da Equipe Uai!rrior de robótica da UNIFEI entre maio/2011 e fevereiro/2013. Participou de um projeto de Iniciação Científica (IC) na Fundação Coordenação de Projetos, Pesquisas e Estudos Tecnológicos (COPPETEC) entre fevereiro/2013 e dezembro/2015 cujo objetivo era analisar técnicas de Visualização da Informação para o contexto governamental. Participou de projetos de pesquisa e Desenvolvimento da Fundação Coordenação de Projetos, Pesquisas e Estudos Tecnológicos (COPPETEC / UFRJ), atuando como líder de equipe no desenvolvimento de Projetos no Centro de Apoio à Políticas de Governo (CAPGov) - COPPE / UFRJ. Atualmente é professora da Universidade Federal de Itajubá - UNIFEI\nFormação Profissional Acadêmica: Graduação em Sistemas de Informação pela Universidade Federal de Itajubá (2015). Mestrado em Engenharia de Sistemas e Computação pelo PESC/COPPE/UFRJ (2018). Doutorado em Engenharia de Sistemas e Computação pelo PESC/COPPE/UFRJ (2024).\nÁreas de Interesse: Banco de Dados, Visualização da Informação, Análise de Dados\nÁreas de conhecimento:\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Participação Eletrônica\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Representação da Informação\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Sistemas de Informação\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Banco de Dados\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Linguagens de Programação\n\nLinhas de pesquisa: Visualização da Informação (INFOVIS), Banco de Dados, Gestão do Conhecimento, Análise de Dados\n\nPalavras-chave: Participação Pública, Ferramentas de participação eletrônica, Democracia Digital, Participação Cidadã, Governo Eletrônico',
  'metadata': {'nome': 'BARBARA PIMENTA CAETANO'}},
 {'id': '3529390',
  'hash': '90a158e4829962381ea72d45f92bbf6098c5bf3c7ff3010051bd5b877539cc35',
  'texto_embedding': 'Resumo: Tenho mestrado em Ciência e Tecnologia da Computação e bacharelado em Sistemas de Informação pela Universidade Federal de Itajubá (UNIFEI), onde também atuei como monitor de disciplinas e participei de projetos que ampliaram minha visão sobre desenvolvimento e arquitetura de sistemas.Durante o mestrado, aprofundei meus estudos em confiabilidade de sistemas, o que resultou na publicação do artigo A Systematic Literature Review on Trustworthiness for Applications Used in eHealth Environments no Journal of Multidisciplinary Healthcare. Essa pesquisa me permitiu compreender como a tecnologia pode ser aplicada de forma ética e segura em contextos sensíveis, reforçando meu interesse por soluções que unam inovação, responsabilidade e impacto social.Minha trajetória profissional começou no desenvolvimento mobile, trabalhando no app Filma Eu!, disponível para Android e iOS. Nesse projeto, participei de todas as etapas do ciclo de vida do produto, da concepção e codificação à publicação e manutenção, o que consolidou minha experiência prática e ampliou minha visão sobre produto e usuário.Atualmente, atuo como engenheiro de software, com interesse em desafios que envolvam desenvolvimento mobile, arquitetura de software e engenharia de sistemas, especialmente em contextos que unem inovação e impacto real.Acredito que a melhor inovação é aquela que realmente melhora a vida das pessoas\nÁreas de conhecimento:\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Desenvolvimento Mobile\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Arquitetura de Software\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Engenharia de Software',
  'metadata': {'nome': 'BRENO DE OLIVEIRA RENO'}},
 {'id': '2127183',
  'hash': 'a4ef6cc69d1aee183814093a416fd1d979a304cbf8717535ebcfa29ec5ef4abd',
  'texto_embedding': 'Resumo: Possui graduação em Ciência da Computação pela Pontifícia Universidade Católica de Minas Gerais (2006), mestrado em Ciências da Computação e Matemática Computacional pela Universidade de São Paulo (2009) e doutorado em Ciências da Computação pela Universidade de São Paulo (2015). Atualmente é professor do magistério superior da Universidade Federal de Itajubá\nÁreas de conhecimento:\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Sistemas de Computação. Especialidade: Sistemas Distribuídos\n\nPalavras-chave: Web Services, SOA, QoS, Composição de Web Services',
  'metadata': {'nome': 'BRUNO TARDIOLE KUEHNE'}},
 {'id': '1887447',
  'hash': '379e18f962c40ffd7af8758dec4e6207a394875e9263da1af0435a6f742b46f2',
  'texto_embedding': 'Resumo: Possui graduação em Engenharia de Controle e Automação pela Universidade Federal de Itajubá (2008), mestrado em Engenharia Elétrica pela Universidade Federal de Itajubá (2011) e doutorado em Engenharia Elétrica pela Universidade Federal de Itajubá (2013). Atualmente é professor do Instituto de Engenharia de Sistemas e Tecnologia da Informação da Universidade Federal de Itajubá. Tem experiência na área de Engenharia Elétrica, com ênfase em Controle de Processos Eletrônicos, Retroalimentação\nFormação Profissional Acadêmica: Graduação em Engenharia de Controle e Automação - 2004 - UNIFEI Mestrado em Engenharia Elétrica (Área de Concentração: Automação e Sistemas Elétricos Industriais)- 2011 - UNIFEI Doutorado em Engenharia Elétrica (Área de Concentração: Automação e Sistemas Elétricos Industriais)- 2013 - UNIFEI\nÁreas de Interesse: Sistemas de Controle:, Controle Multivariável e Robusto, Controle Adaptativo e Preditivo, Aplicações de Sistemas de Controle, Instrumentação para Sistemas de Controle\nÁreas de conhecimento:\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Eletrônica Industrial, Sistemas e Controles Eletrônicos. Especialidade: Controle de Processos Eletrônicos, Retroalimentação\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Eletrônica Industrial, Sistemas e Controles Eletrônicos. Especialidade: Automação Eletrônica de Processos Elétricos e Industriais\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Medidas Elétricas, Magnéticas e Eletrônicas; Instrumentação. Especialidade: Sistemas Eletrônicos de Medida e de Controle\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Circuitos Elétricos, Magnéticos e Eletrônicos\n\nLinhas de pesquisa: Sistemas Dinâmicos Multivariáveis\n\nPalavras-chave: Princípio de Recuperação da Malha Objetivo, Controladores H2 e Hoo, Controle LQG, LTR, Controle Multivarável e Robusto, Controladores PID, Resposta em frequência, Sistemas de fase não-monótona, Sintonia analítica de compensadores',
  'metadata': {'nome': 'CAIO FERNANDES DE PAULA'}},
 {'id': '1545021',
  'hash': 'e7d3e102067df3e49f76c41bf7f420fb79a33901fc270c467b58efee6a095f9f',
  'texto_embedding': 'Resumo: Possui graduação em Engenharia Elétrica pela Universidade Federal de Itajubá (2001), mestrado em Engenharia Elétrica pela Universidade Federal de Itajubá (2002) e doutorado em Engenharia Elétrica pela Universidade Federal de Itajubá (2006). Atualmente é professor associado 4 da Universidade Federal de Itajubá. Tem experiência na área de Engenharia Elétrica, com ênfase em Automação Eletrônica de Processos Elétricos e Industriais, atuando principalmente nos seguintes temas: inteligência artificial, sistemas elétricos, sistema especialista, controle inteligente e planejamento inteligente\nFormação Profissional Acadêmica: 1996 - Técnico de Eletrônica na ETEFMC; 2001 - Engenheiro Eletricista com Ênfase em Eletrotécnica na EFEI; 2002 - Mestre em Engenharia Elétrica na UNIFEI; 2006 - Doutor em Engenharia Elétrica na UNIFEI.\nÁreas de Interesse: SmartGrid, sistemas embarcados inteligentes, planejamento inteligente, veículos autônomos e engenharia biomédica.\nÁreas de conhecimento:\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Eletrônica Industrial, Sistemas e Controles Eletrônicos. Especialidade: Automação Eletrônica de Processos Elétricos e Industriais\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Computação\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Medidas Elétricas, Magnéticas e Eletrônicas; Instrumentação. Especialidade: Instrumentação Eletrônica\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Eletrônica Industrial, Sistemas e Controles Eletrônicos. Especialidade: Eletrônica Industrial\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Eletrônica Industrial, Sistemas e Controles Eletrônicos. Especialidade: Controle de Processos Eletrônicos, Retroalimentação\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Sistemas Elétricos de Potência. Especialidade: Transmissão da Energia Elétrica, Distribuição da Energia Elétrica\n\nLinhas de pesquisa: Aplicação de Sistemas Inteligentes em Dispositivos Móveis, Aplicação de Sistemas Inteligentes em Sistemas Embarcados, Aplicação de Sistemas Inteligentes na Engenharia de Controle e Automação, Formulação de Modelos Matemáticos para a Engenharia de Controle e Automação, Desenvolvimento e Aplicação de Lógicas Não-Clássicas, Desenvolvimento de Conceitos Teóricos em Inteligência Aritificial, Visão Computacional e Técnicas Avançadas de Reconhecimento de Padrões\n\nPalavras-chave: Agentes Inteligente, Inteligência Artificial, Sistema Elétrico, Mineração de Dados, Transformação da Classe de Tensão, Sistemas Elétricos, Análise Técnico-Econômica',
  'metadata': {'nome': 'CARLOS HENRIQUE VALERIO DE MORAES'}},
 {'id': '1795095',
  'hash': '0766a8959a68366395d9eff781289d467d8433391a247d25dbbee2068a4f45f3',
  'texto_embedding': 'Resumo: Graduação em Engenharia Elétrica pela EFEI - Escola Federal de Engenharia de Itajubá (1989). Mestre em Engenharia Elétrica - Área de Automação e Sistemas Elétricos Industriais pela UNIFEI - Universidade Federal de Itajubá (2009). Experiência em gestão administrativa e industrial de pequenas e médias empresas. Participações como pesquisador em projetos de P D junto a empresas do setor elétrico. Atualmente é professor Adjunto junto ao IESTI da UNIFEI. Interesse nas seguintes áreas de conhecimento: Automação Industrial e de Sistemas Elétricos de potência. Confiabilidade, Segurança e Proteção cibernética em Sistemas de Automação. Sistemas tolerante a falhas para auxilio a tomada de decisão em sistemas de automação\nÁreas de conhecimento:\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Eletrônica Industrial, Sistemas e Controles Eletrônicos. Especialidade: Automação Eletrônica de Processos Elétricos e Industriais\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Medidas Elétricas, Magnéticas e Eletrônicas; Instrumentação. Especialidade: Sistemas Eletrônicos de Medida e de Controle\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Medidas Elétricas, Magnéticas e Eletrônicas; Instrumentação. Especialidade: Instrumentação Eletrônica\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Segurança cibernética em sistemas de automação no setor industrial e elétrico',
  'metadata': {'nome': 'CARLOS WALDECIR DE SOUZA'}},
 {'id': '1810770',
  'hash': 'ac83b926922d8a43d53c065a7f000a8220a331e1873558f498e7280e516469d9',
  'texto_embedding': 'Resumo: Possui graduação em Engenharia Elétrica pela Universidade Federal de Itajubá (2002). Concluiu o mestrado (2004) e o doutorado (2008) em Engenharia Elétrica, área de concentração telecomunicações, pela USP - Universidade de São Paulo. Em 2009, fez o pós-doutoramento no exterior, junto ao Grupo de Nanofotônica da Universidade de Cornell, Ithaca, EUA. Em 2010 foi bolsista Fapesp de pós-doutorado na Universidade Presbiteriana Mackenzie. Em 2012 trabalhou como pesquisador visitante, com bolsa Erasmus Mundus, no centro de pesquisa IMEC, em Leuven, Bélgica. No ano de 2016 recebeu Certificação Profissional RFID - IDentificação por Rádio Frequência. Em 2024 fez o pós doutoramento na COPL - Laval University, Quebec-CA. Atualmente é professor Associado IV, na área de sistemas de telecomunicações e eletromagnetismo aplicado, Diretor de Pesquisa e Pró-reitor Adjunto de Pesquisa e Pós-graduação na Universidade Federal de Itajubá. Foi diretor adjunto de Relações Internacionais da UNIFEI entre 05/2018 a 08/2019. No período de 09/2019 a 12/2020 atuou como Pró-reitor Adjunto de Pesquisa e Pós-graduação da UNIFEI. Tem experiência na área de engenharia elétrica, com ênfase em telecomunicações, atuando, principalmente, nos seguintes temas: comunicações ópticas, fotônica, fibras ópticas de cristal fotônico e fotônica do silício\nFormação Profissional Acadêmica: Possui graduação em Engenharia Elétrica pela Universidade Federal de Itajubá (2002). Concluiu o mestrado (2004) e o doutorado (2008) em Engenharia Elétrica, área de concentração telecomunicações, pela USP - Universidade de São Paulo. Em 2009, fez o pós-doutoramento no exterior, junto ao Grupo de Nanofotônica da Universidade de Cornell, USA\nÁreas de Interesse: Tem experiência na área de engenharia elétrica, com ênfase em telecomunicações, atuando, principalmente, nos seguintes temas: comunicações ópticas, fotônica, fibras ópticas de cristal fotônico e fotônica do silício\nÁreas de conhecimento:\nGrande área: Engenharias. Área: Engenharia Elétrica\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Telecomunicações\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Telecomunicações. Especialidade: Sistemas de Telecomunicações\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Nanofotônica\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Telecomunicações. Especialidade: Teoria Eletromagnetica, Microondas, Propagação de Ondas, Antenas\n\nPalavras-chave: Fibras ópticas microestruturadas, Comunicações Ópticas, Métodos Numéricos',
  'metadata': {'nome': 'DANILO HENRIQUE SPADOTI'}},
 {'id': '1374755',
  'hash': '9b69b0307be425a7534ca46401a6caa7276494643b6c6f9c78079d77753da00c',

In [33]:
professores_valores_denso_lexical = {}  
for professor in professores_busca_perfis:
        
    texto_transformado = rodar_bgeM3(modelo,professor.get("texto_embedding"))

    professores_valores_denso_lexical[professor["id"]] = texto_transformado

In [194]:
def criar_perfils_disciplinas(disciplinas) -> list[dict]:
    disciplina_texto = []
    for disciplina in disciplinas:
        texto_embedding = montar_texto_disciplina(disciplina)
        trabalho_transformado = {
            "id" : disciplina['idSigaa'], 
            "hash" : gerar_hash(texto_embedding),
            "texto_embedding": texto_embedding,
            "metadata" : {
               "nome": disciplina['nome'],
               "codigo": disciplina["codigo"]

            }
        }
        disciplina_texto.append(trabalho_transformado)
        
    return disciplina_texto

In [195]:
disciplinas_perfil_busca = criar_perfils_disciplinas(disciplinas_dados)

In [197]:
disciplinas_valores_denso_lexical = {}  
for disciplina in disciplinas_perfil_busca:

    texto_transformado = rodar_bgeM3(modelo,disciplina.get("texto_embedding"))

    disciplinas_valores_denso_lexical[disciplina["id"]] = texto_transformado

Qdrant

In [ ]:
import uuid

def qdrant_id(id):
    return str(uuid.uuid5(uuid.NAMESPACE_URL, f"{id}"))

In [ ]:
def conectar_qdrant(url):
    return QdrantClient(url=url)

def criar_banco_qdrant(client_qdrant, nome):
    client_qdrant.create_collection(
        collection_name= nome,
        vectors_config={
            "dense": VectorParams(size=1024, distance=Distance.COSINE)},
        sparse_vectors_config={
            "sparse": SparseVectorParams(),
        },
    )

def atualizar_perfis(perfis_transformados, client_qdrant):

    professores_para_atualizar = []

    for perfil in perfis_transformados:

        professor_id = qdrant_id(perfil.get("id"))
        hash_atual = perfil.get("hash")


        busca = client_qdrant.retrieve(
            collection_name="professores",
            ids=[professor_id],
            with_payload=True
        )
        if not busca:
            professores_para_atualizar.append({
                "perfil": perfil,
            })
            continue
        
        payload_qdrant = busca[0].payload

        hash_salvo = payload_qdrant.get("hash")

        if hash_salvo != hash_atual:
                professores_para_atualizar.append({"perfil": perfil})

    return professores_para_atualizar

In [ ]:
def adicionar_trabalhos_qdrant(client_qdrant, conteudo, resultados, collection = ""):
    points = []
    for objeto in conteudo:
        
        objeto_id  = objeto.get('id')
        
        resultado = resultados[objeto_id]

        sparse = resultado["sparse"]

        sparse_indices = [int(k) for k in sparse.keys()]
        sparse_values = [float(v) for v in sparse.values()]
            
        dense = resultado["dense"]
            
        points.append(
            PointStruct(
                id=qdrant_id(objeto.get("id")),
                vector={
                    "dense": dense.tolist(),
                    "sparse": SparseVector(indices=sparse_indices, values=sparse_values),
                },
                # metadados
                payload={
                    "id": objeto.get("id"),
                    "titulo":  objeto.get("metadata", {}).get("titulo"),
                    "ano": objeto.get("metadata", {}).get("ano"),
                    "hash":objeto.get("hash")
                }
            )
        )
            
    client_qdrant.upsert(collection_name=collection, points=points)

In [235]:
def adicionar_professores_qdrant(client_qdrant, professores, resultados, collection = ""):
    points = []
    for objeto in professores:
        
        objeto_id  = objeto.get('id')
        
        resultado = resultados[objeto_id]

        sparse = resultado["sparse"]

        sparse_indices = [int(k) for k in sparse.keys()]
        sparse_values = [float(v) for v in sparse.values()]
            
        dense = resultado["dense"]
            
        points.append(
            PointStruct(
                id=qdrant_id(objeto.get("id")),
                vector={
                    "dense": dense.tolist(),
                    "sparse": SparseVector(indices=sparse_indices, values=sparse_values),
                },
                # metadados
                payload={
                    "id": objeto.get("id"),
                    "nome":  objeto.get("metadata", {}).get("nome"),
                    "hash" :  objeto.get("hash")
                }
            )
        )
            
    client_qdrant.upsert(collection_name=collection, points=points)

In [ ]:
def adicionar_disciplinas_qdrant(
    client_qdrant,
    conteudo,
    resultados,
    collection="",
    batch_size=50
):
    points = []

    for objeto in conteudo:

        objeto_id = objeto.get("id")
        resultado = resultados[objeto_id]

        sparse = resultado["sparse"]

        sparse_indices = [int(k) for k in sparse.keys()]
        sparse_values = [float(v) for v in sparse.values()]

        dense = resultado["dense"]

        points.append(
            PointStruct(
                id=qdrant_id(objeto_id),
                vector={
                    "dense": dense.tolist(),
                    "sparse": SparseVector(
                        indices=sparse_indices,
                        values=sparse_values
                    ),
                },
                payload={
                    "id": objeto_id,
                    "nome": objeto.get("metadata", {}).get("nome"),
                    "hash": objeto.get("hash")
                }
            )
        )
    #Enviando aos poucos já que tem muitas disciplinas
    for i in range(0, len(points), batch_size):
        batch = points[i:i + batch_size]

        client_qdrant.upsert(
            collection_name=collection,
            points=batch,
            wait=True
        )

In [39]:
# aplica filtro do payload antes da busca (colocar antes de adicionar dados)
def criacao_payload_filter(client, collection, field, tipo = models.PayloadSchemaType.INTEGER):
    client.create_payload_index(
        collection_name=collection,
        field_name=field,
        field_schema=tipo,
    )

Conectando ao Qdrant no Docket

In [31]:
client_qdrant = conectar_qdrant("http://localhost:6333")

In [198]:
criar_banco_qdrant(client_qdrant, "ics")

KeyboardInterrupt

In [ ]:
adicionar_trabalhos_qdrant(client_qdrant, ics_transformadas, ics_perfis_busca, collection = "ics")

In [171]:
criar_banco_qdrant(client_qdrant, "professores")

In [ ]:
adicionar_professores_qdrant(client_qdrant, professores_busca_perfis, professores_valores_denso_lexical, collection = "professores")

Qdrant cloud

In [203]:
from qdrant_client import QdrantClient, models
import os

client = QdrantClient(url=os.getenv("QDRANT_URL"), api_key=os.getenv("QDRANT_API_KEY"))

In [204]:
# Quick health check
collections = client.get_collections()
print(f"Connected to Qdrant Cloud: {len(collections.collections)} collections")

Connected to Qdrant Cloud: 3 collections

In [65]:
criar_banco_qdrant(client,"professores")

In [66]:
adicionar_professores_qdrant(client,professores_busca_perfis,professores_valores_denso_lexical, collection="professores")

In [238]:
criar_banco_qdrant(client,"iniciacao_cientifica")

In [237]:
client.delete_collection("iniciacao_cientifica")

True

In [239]:
criacao_payload_filter(client, "iniciacao_cientifica", "ano")

In [240]:
adicionar_trabalhos_qdrant(client,ics_perfis_busca , ics_valores_denso_lexical, collection = "iniciacao_cientifica")

In [270]:
client.delete_collection("disciplinas")

True

In [271]:
criar_banco_qdrant(client,"disciplinas")

In [272]:
adicionar_disciplinas_qdrant(client,disciplinas_perfil_busca , disciplinas_valores_denso_lexical, collection = "disciplinas")

Enviando 0 - 50 de 1484
Enviando 50 - 100 de 1484
Enviando 100 - 150 de 1484
Enviando 150 - 200 de 1484
Enviando 200 - 250 de 1484
Enviando 250 - 300 de 1484
Enviando 300 - 350 de 1484
Enviando 350 - 400 de 1484
Enviando 400 - 450 de 1484
Enviando 450 - 500 de 1484
Enviando 500 - 550 de 1484
Enviando 550 - 600 de 1484
Enviando 600 - 650 de 1484
Enviando 650 - 700 de 1484
Enviando 700 - 750 de 1484
Enviando 750 - 800 de 1484
Enviando 800 - 850 de 1484
Enviando 850 - 900 de 1484
Enviando 900 - 950 de 1484
Enviando 950 - 1000 de 1484
Enviando 1000 - 1050 de 1484
Enviando 1050 - 1100 de 1484
Enviando 1100 - 1150 de 1484
Enviando 1150 - 1200 de 1484
Enviando 1200 - 1250 de 1484
Enviando 1250 - 1300 de 1484
Enviando 1300 - 1350 de 1484
Enviando 1350 - 1400 de 1484
Enviando 1400 - 1450 de 1484
Enviando 1450 - 1484 de 1484

Aluno fez preencheu o formulário

In [273]:
aluno_texto = "Gostaria de desenvolver um projeto com inteligência artificial e programação embarcada"
aluno = modelo.encode(aluno_texto, return_dense=True, return_sparse=True)
embedding_aluno = aluno['dense_vecs']
lexical_aluno = aluno['lexical_weights']

In [241]:
def busca_hibrida_qdrant(client_qdrant,collection,dense,sparse, limit=50):
    sparse_query = SparseVector(
        indices=[int(k) for k in sparse.keys()],
        values=[float(v) for v in sparse.values()],
    )

    prefetch = [
        Prefetch(
            query=dense.tolist(),
            using="dense",
            limit=limit
        ),
        Prefetch(
            query=sparse_query,
            using="sparse",
            limit=limit
        )
    ]

    results = client_qdrant.query_points(
        collection_name=collection,
        prefetch=prefetch,
        query=FusionQuery(
            fusion=Fusion.RRF
        ),
        limit=limit,
        with_payload=True
    )
    return results.points

In [242]:
busca_realizada_ics = busca_hibrida_qdrant(client,"iniciacao_cientifica", embedding_aluno, lexical_aluno, limit=50)

In [243]:
for point in busca_realizada_ics:
    print(
        point.payload["id"],
        point.payload["titulo"],
        point.score
    )

f92d111e5241 Estruturação de hardware e software para desenvolvimento de um agv 0.6111111
330dbb5265cd DETECÇÃO DE PRAGAS EM LAVOURAS COM REDES NEURAIS CONVOLUCIONAIS EM SISTEMAS EMBARCADOS 0.5416667
6d9b570e8513 ESTUDO DE SISTEMAS EMBARCADOS NA AGRICULTURA DIGITAL 0.4166667
135b69c36144 DESENVOLVIMENTO DE RECURSOS EDUCACIONAIS ABERTOS SOBRE MICRORREDES 0.41025642
8f39dd8786ae Desenvolvimento do firmware para acionamento e aquisição de dados para veículos autônomos 0.39285713
9617879d2744 Estudo de algoritmo de controle de trajetórias de uma Aeronave Remotamente Pilotada 0.36904764
f0890bd4eb6a Estudo e desenvolvimento de uma microarquitetura RISC-V baseado no ISA RV32I. 0.325
d654c8a463bc Segmentação Semântica Integrada ao ROS2 para Aplicações em Veículos Autônomos 0.23376624
a23a21b54ceb Sistema de armazenamento de energia combinado com geração fotovoltaica operando como formador de rede ou supridor de rede 0.22222222
92d0c1e746e0 APLICAÇÃO DE TÉCNICAS DE INTELIGÊNCIA ARTIFICIAL PARA CONTROLE DE CONVERSOR DC-DC 0.21014494
7492ba0c189a BIT A BIT : UM JOGO DE TABULEIRO SOBRE O UNIVERSO DA COMPUTAÇÃO 0.17045455
f001be6c8d33 BENCHMARK DE DESEMPENHO E PORTABILIDADE DO WEBASSEMBLY EM ALGORITMOS COMPUTACIONAIS 0.15555556
198d41e77b76 DESENVOLVIMENTO DE INTERFACE ANALÓGICA E DIGITAL ÓPTICA PARA PESQUISA E ENSINO DE CONVERSORES ELETRÔNICOS 0.13383839
fa6617353a7b UM ESTUDO DA TRANSFERÊNCIA DE APRENDIZADO EMPREGANDO MODELOS DE APRENDIZADO PROFUNDO: CONCEITOS, TÉCNICAS E APLICAÇÕES 0.13090909
ad87b6f82193 ESTUDO DO MANIPULADOR ROBÓTICO TM5X-900 E DA INTEGRAÇÃO DO EQUIPAMENTO COM ATUADORES, SENSORES E CONTROLADORES EXTERNOS 0.12179488
e8343c0e98ff SMARTIZAÇÃO DE UM DISPENSADOR DE MEDICAÇÃO COMERCIAL POR MEIO DE UM SISTEMA DE COMUNICAÇÃO IOT E CLASSIFICAÇÃO POR FERRAMENTA DE APRENDIZADO DE MÁQUINA 0.11396012
158b1b041328 AVALIAÇÃO DE TÉCNICAS META-HEURÍSTICAS APLICADAS AOS SISTEMAS ELÉTRICOS DE POTÊNCIA 0.10644258
674b91450980 VULNERABILIDADES E CONTRA-MEDIDAS NA UTILIZAÇÃO DE BIOMETRIA UTILIZANDO INTELIGÊNCIA ARTIFICIAL 0.1
70d66ca8d9f7 COMPUTAÇÃO QUÂNTICA APLICADA À HARDWARE CONFIGURÁVEL COM FOCO EM SEGURANÇA DA INFORMAÇÃO 0.09107143
3bccbfa2d90e Uso de uma CNN para mapeamento de bioindicadores em ambiente de pesquisa laboratorial 0.083333336
7b36c0e3d1ed PROGRAMAÇÃO E TESTE DE LEIS DE CONTROLE EM QUADRICÓPTERO DE 3 GDL 0.082499996
d20805e76bba DESENVOLVIMENTO DE UMA PLATAFORMA BASEADA EM SISTEMA OPERACIONAL EM TEMPO REAL PARA UM MÓDULO DE GERENCIAMENTO ENERGÉTICO 0.07631579
b6e8955a7f32 DESENVOLVIMENTO DE FUNCIONALIDADES PARA GAMIFICAÇÃO EM AMBIENTE DE REALIDADE VIRTUAL 0.0751634
e5bd86f84b37 ESTUDO E FAMILIARIZAÇÃO COM DISPOSITIVOS DSP C2000 VISANDO IMPLEMENTAÇÃO DE CONTROLADORES PARA CONVERSORES BASEADOS EM ELETRÔNICA DE POTÊNCIA 0.071428575
c70f684b7b3e Antena mimo dual-band de microfita para aplicação em wireless 5g 0.071428575
80b399b666f1 AVALIAÇÃO DE TÉCNICAS META-HEURÍSTICAS APLICADAS AOS SISTEMAS ELÉTRICOS DE POTÊNCIA 0.068478264
992b94fcbacd Um estudo da transferência de aprendizado empregando modelos de aprendizado profundo: aplicação de LLMs (Large Language Models) no contexto educacional 0.06666667
1b824c3c9647 PERDA DE SINCRONISMO EM GERADORES SÍNCRONOS CONECTADOS A LTS COM FACTS: UM MÉTODO DE CLASSIFICAÇÃO PELA DERIVADA DA POTÊNCIA 0.06666667
efc40bb6e0cf Balança IoT com LoRa: Monitoramento Remoto de Peso 0.06350806
06685c762ee1 CONVERSORES MULTICELULARES DE ALTA BANDA PASSANTE PARA INTEGRAÇÃO DE FONTES DE GERAÇÃO DE ENERGIA 0.0627451
618c08cdde4c Estudo e desenvolvimento de periféricos internos para trabalhar em conjunto com microarquiteturas RISC-V baseadas no ISA RV32I. 0.05882353
1748a04c0043 O USO DE MACHINE LEARNING NA PREVISÃO DE SECAS EM DIFERENTES ESCALAS DE TEMPO 0.05831363
6d94f3be5395 CAFÉ PARA TODOS 0.05263158
5e414e1e0ded MODELAGEM E ANÁLISE TÉCNICA DA INTEGRAÇÃO DE GERAÇÃO DISTRIBUÍDA SUSTENTÁVEL PV NO CAMPUS DA UNIFEI - ITAJUBÁ 0.05263158
f8977f97857e SISTEMA DE INTEGRAÇÃO MÉDICO-PACIENTE 0.05
95aadad998a8 PROJETO DE UMA ANTENA MIMO MICROFITA COMPACTA E DE BANDA DUPLA PARA BANDA LARGA 0.04761905
6eb11d095a65 Medição de Energia Elétrica à Longa Distância 0.045454547
9ff8a178dbdc DESENVOLVIMENTO DE UM SIMULADOR HÍBRIDO PARA FUTEBOL DE ROBÔS 0.043998085
247aeac7fb96 ANÁLISE COMPARATIVA DAS SOLUÇÕES DE CRIPTOGRAFIA PÓS-QUÂNTICA DISPONÍVEIS NO MERCADO 0.041666668
8c0815440e89 DESENVOLVIMENTO DE PERCEPÇÃO PARA VEÍCULOS AUTÔNOMOS 0.04
417eae0df1af ANÁLISE E IMPLEMENTAÇÃO DE CIRCUITO NEUROMÓRFICO UTILIZANDO A ARQUITETURA ELM (EXTREME LEARNING MACHINE) EM HARDWARE 0.03846154
1634347dce9b ACESSIBILIDADE E INCLUSÃO EM JOGOS DIGITAIS: UM MAPEAMENTO SISTEMÁTICO DA LITERATURA BRASILEIRA 0.035714287
77c7592eff6c UM ESTUDO DA TRANSFERÊNCIA DE APRENDIZADO EMPREGANDO MODELOS DE APRENDIZADO PROFUNDO: APLICAÇÕES DE PROCESSAMENTO DE LINGUAGEM NATURAL 0.03448276
0afeaab59847 Aplicação de otimização por enxame de partículas para a alocação ótima de filtros ativos em sistemas elétricos de potência 0.03448276
f03e244a0145 EFICÁCIA DE MODELOS DE SÉRIES TEMPORAIS NA PREVISÃO DE CONSUMO PARA ENERGIA FOTOVOLTAICA: SARIMA e PROPHET 0.033333335
9b3189cbc1da IMPLEMENTAÇÃO E VALIDAÇÃO DE MISSÕES AUTÔNOMAS DE DRONES UTILIZANDO ROS2 E RVIZ 0.032258064
9c7d841480d3 SISTEMA DE CONTROLE DE ESTOQUE COM APLICAÇÃO PARA DESKTOP E LEITOR DE CÓDIGO DE BARRAS UTILIZANDO ESP32 E COMUNICAÇÃO VIA WIFI 0.03125
f55732890b00 Aplicação da tecnologia lorawan como solução para transmissão de dados de sensor de nível e temperatura 0.030303031
8e3cd7fa953f DESENVOLVIMENTO DE RECURSOS DIGITAIS MULTIMODAIS PARA ALFABETIZAÇÃO ENERGÉTICA 0.030303031
c854148965a4 DESENVOLVIMENTO DE KIT-DIDÁTICO DE CONTROLE DE PONTE H USANDO FPGA 0.029411765

In [220]:
busca_realizada_perfis_professores = busca_hibrida_qdrant(client,"professores",embedding_aluno,lexical_aluno,limit = 50)

In [221]:
for point in busca_realizada_perfis_professores:
    print(
        point.payload["id"],
        point.payload["nome"],
        point.score
    )

1545021 CARLOS HENRIQUE VALERIO DE MORAES 0.625
1682528 THATYANA DE FARIA PIOLA SERAPHIM 0.54761904
1967206 LUCIANO BERTINI 0.5
1732597 RODRIGO MAXIMIANO ANTUNES DE ALMEIDA 0.4761905
1374755 DECIO RENNO DE MENDONCA FARIA 0.35
3529390 BRENO DE OLIVEIRA RENO 0.3125
394747 LUIZ EDIVAL DE SOUZA 0.25555557
394714 JOSE ALBERTO FERREIRA FILHO 0.23809525
3443612 BARBARA PIMENTA CAETANO 0.22619048
1097837 GABRIEL CIRAC MENDES DE SOUZA 0.2
1543328 ENZO SERAPHIM 0.1625
395119 TALES CLEBER PIMENTA 0.15725806
1457656 EDMILSON MARMO MOREIRA 0.15277778
2195171 ROBSON LUIZ MORENO 0.15
2642873 KLEBER ROBERTO DA SILVA SANTOS 0.13968255
2019312 ODILON DE OLIVEIRA DUTRA 0.13247864
3150657 GABRIEL ANTONIO FANELLI DE SOUZA 0.12692308
1999579 JOAO PAULO REUS RODRIGUES LEITE 0.124242425
1862488 JEREMIAS BARBOSA MACHADO 0.124060154
6394694 EGON LUIZ MULLER JUNIOR 0.11948052
1310498 ANDRE BERNARDI 0.116666675
1560417 LUIS HENRIQUE DE CARVALHO FERREIRA 0.09882353
1666035 LEONARDO BRESEGHELLO ZOCCAL 0.09453782
1887447 CAIO FERNANDES DE PAULA 0.08388158
3104470 LUIZ LENARTH GABRIEL VERMAAS 0.0787037
1634986 EDVARD MARTINS DE OLIVEIRA 0.07796102
2269653 MATEUS AUGUSTO FAUSTINO CHAIB JUNQUEIRA 0.07464608
2372188 GUILHERME DE SOUSA BASTOS 0.07289003
2127183 BRUNO TARDIOLE KUEHNE 0.07248157
394764 MAURILIO PEREIRA COUTINHO 0.07225806
3525710 RODRIGO DE PAULA RODRIGUES 0.06926407
2256795 ROBSON BAUWELZ GONZATTI 0.06787331
1814241 RONDINELI RODRIGUES PEREIRA 0.06458333
2234207 ANA PAULA SIQUEIRA SILVA DE ALMEIDA 0.06285179
1795095 CARLOS WALDECIR DE SOUZA 0.06226054
2576624 GISCARD FRANCIMEIRE CINTRA VELOSO 0.06029285
2230762 FERNANDO HENRIQUE DUARTE GUARACY 0.05844156
3297076 WILSON CESAR SANT'ANA 0.05661882
3524775 JUAN PABLO OCHOA AVILES 0.055944055
3288575 RAMON MAIA BORGES 0.05216802
1810770 DANILO HENRIQUE SPADOTI 0.05
1062611 ENIO ROBERTO RIBEIRO 0.049571604
2195502 GUSTAVO DELLA COLLETTA 0.04945055

In [341]:
busca_realizada_disciplinas = busca_hibrida_qdrant(client,"disciplinas",embedding_aluno,lexical_aluno,limit = 100)

In [342]:
for point in busca_realizada_disciplinas:
    print(
        point.payload["id"],
        point.payload["nome"],
        point.score
    )

5651 PROGRAMAÇÃO PARA SISTEMAS EMBARCADOS 0.75
5300 LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA 0.625
5295 PROGRAMAÇÃO EMBARCADA 0.4761905
5310 INTELIGÊNCIA ARTIFICIAL 0.35833335
5314 LABORATÓRIO DE INTELIGÊNCIA ARTIFICIAL 0.28125
5673 APRENDIZADO BASEADO EM PROJETO III 0.2361111
29724 Inteligência Artificial 0.2212766
7677 Programação Avançada 0.2
29725 Inteligência Artificial (Prática) 0.1969697
30006 Programação Avançada 0.16666667
7265 MANUFATURA INTEGRADA POR COMPUTADOR 0.14285715
5565 Sistemas Embarcados com ARM 7 0.124390244
47044 INTELIGÊNCIA ARTIFICIAL APLICADA 0.11111111
46958 PROJETO DE SOFTWARE 0.10240334
29452 Programação Aplicada 0.10220126
46945 PROJETO INTEGRADOR DE AUTOMAÇÃO 0.1
7667 PROGRAMAÇÃO ORIENTADA A OBJETOS 0.09090909
5676 LABORATÓRIO DE PROGRAMAÇÃO 0.08703704
49442 INTELIGÊNCIA ARTIFICIAL II 0.083333336
5243 PROGRAMAÇÃO APLICADA 0.082633056
5245 LABORATÓRIO DE PROGRAMAÇÃO APLICADA 0.077030815
5240 PROGRAMAÇÃO ORIENTADA A OBJETOS 0.07692308
581 PROJETO DE CIRCUITOS INTEGRADOS DIGITAIS 0.07692308
29453 PROGRAMAÇÃO APLICADA (PRÁTICA) 0.0734127
731 PROJETO DE CIRCUITOS INTEGRADOS DIGITAIS 0.071428575
46959 LABORATÓRIO DE PROJETO DE SOFTWARE 0.071428575
48864 PROJETO E IMPLEMENTAÇÃO DE INTERFACE GRÁFICA COM PYTHON 0.067320265
29444 Programação Orientada a Objetos 0.06666667
165 PROJETO DE CIRCUITOS INTEGRADOS DIGITAIS 0.06666667
149 PROJETO DE CIRCUITOS INTEGRADOS DIGITAIS 0.0625
29445 Programação Orientada a Objetos (Prática) 0.0625
583 PROJETO DE CIRCUITOS INTEGRADOS DIGITAIS 0.05882353
46773 TINYML - APRENDIZADO DE MÁQUINA APLICADO PARA DISPOSITIVOS IOT EMBARCADOS 0.055454545
5199 PROJETO DE DISPOS. E CIRCUITOS INTEGRADOS 0.055454545
5242 LABORATÓRIO DE PROGRAMAÇÃO ORIENTADA A OBJETOS 0.05263158
48863 PROJETO E IMPLEMENTAÇÃO DE INTERFACE GRÁFICA COM JAVA SWING 0.05263158
7446 PROGRAMAÇÃO EM TEMPO REAL 0.05
47041 INTELIGÊNCIA ARTIFICIAL 0.04761905
5098 LABORATÓRIO DE MICROPROCESSADORES/MICROCONTROLADORES 0.047183435
5219 LABORATÓRIO DE TÉCNICAS DE PROGRAMAÇÃO 0.04347826
4768 LINGUAGENS DE PROGRAMAÇÃO 0.04347826
5301 LABORATÓRIO DE PROGRAMAÇÃO APLICADA 0.041666668
5678 FUNDAMENTOS DE PROGRAMAÇÃO 0.041666668
46983 PARADIGMAS DE PROGRAMAÇÃO 0.04
46004 DESIGN OF DIGITAL INTEGRATED CIRCUITS 0.04
46850 MARATONA DE PROGRAMAÇÃO I 0.03846154
7396 PROGRAMAÇÃO APLICADA 0.03846154
29516 MARATONA DE PROGRAMAÇÃO I 0.037037037
46170 ADVANCED CMOS ANALOG INTEGRATED CIRCUIT DESIGN 0.035714287
29499 Programação de Dispositivos Móveis (Prática) 0.035714287
5085 INFORMÁTICA PARA CONTROLE E AUTOMAÇÃO I 0.03448276
29517 MARATONA DE PROGRAMAÇÃO I (PRÁTICA) 0.03448276
45928 ARQUITETURA DE COMPUTADORES DIGITAIS 0.034313727
29256 Microprocessadores 0.033820346
5653 LABORATÓRIO DE PROGRAMAÇÃO PARA SISTEMAS EMBARCADOS 0.033333335
46597 ORGANIZAÇÃO INDUSTRIAL E MANUFATURA DE PRODUTOS ELETRÔNICOS 0.033333335
46932 AUTOMAÇÃO DE PROCESSOS 0.033156805
5194 Computadores Digitais 0.032258064
5108 MANUFATURA INTEGRADA POR COMPUTADOR E ROBÓTICA 0.032155797
46982 DESENVOLVIMENTO DE SISTEMAS WEB 0.03125
29257 Microprocessadores (Prática) 0.030952383
46851 MARATONA DE PROGRAMAÇÃO II 0.030303031
5663 APRENDIZADO BASEADO EM PROJETO I 0.029917121
29498 Programação de Dispositivos Móveis 0.029411765
29587 MARATONA DE PROGRAMAÇÃO II (PRÁTICA) 0.028571429
1034 PROJETOS DE CIRCUITOS INTEGRADOS DIGITAIS 0.028571429
5094 MICROPROCESSADORES/MICROCONTROLADORES 0.028495442
29985 MICROCONTROLADORES (PRÁTICA) 0.028068138
5223 Compiladores 0.027777778
46968 DESENVOLVIMENTO DE PROJETO DE SOFTWARE 0.027777778
5286 LINGUAGEM DE PROGRAMAÇÃO 0.027027028
29728 TÓPICOS ESPECIAIS EM PROGRAMAÇÃO 0.027027028
5308 PROJETO DE SOFTWARE 0.026494566
5667 Gestão de Projetos 0.02631579
30007 Programação Avançada (Prática) 0.02631579
28592 Organização de Computadores 0.025978409
29586 Maratona de Programação II 0.025641026
5690 LABORATÓRIO DE ELETRÔNICA DIGITAL II 0.025641026
5208 COMPUTADORES DIGITAIS 0.025561705
29729 TÓPICOS ESPECIAIS EM PROGRAMAÇÃO (PRÁTICA) 0.025
5215 Algoritmos e Estrutura de Dados 0.024390243
5200 PROJETO DE SISTEMAS VLSI 0.023822792
29356 INTRODUÇÃO A ROBÓTICA 0.023809524
5297 LABORATÓRIO DE TÉCNICAS DE PROGRAMAÇÃO 0.023255814
6829 MARATONA DE PROGRAMAÇÃO 0.022727273
902 AUTOMAÇÃO INTELIGENTE 0.022727273
144 AUTOMAÇÃO INTELIGENTE 0.022222223
5121 Sistemas de Tempo Real 0.022222223
160 AUTOMAÇÃO INTELIGENTE 0.02173913
28593 Organização de Computadores (Prática) 0.021440037
29661 TÓPICOS ESPECIAIS EM PROGRAMAÇÃO III (PRÁTICA) 0.021276595
29251 Automação e Supervisão Sistemas Industriais I (Prática) 0.020833334
5395 Projeto em Informática Industrial I 0.020408163
7050 INFORMÁTICA APLICADA A CONTROLE E AUTOMAÇÃO 0.020408163
45980 AUTOMAÇÃO DE PROCESSOS INDUSTRIAIS I 0.02
29492 Tópicos Especiais I 0.02
29660 TÓPICOS ESPECIAIS EM PROGRAMAÇÃO III 0.01923077
5296 PROGRAMAÇÃO APLICADA 0.01923077
29510 Tópicos Especiais III 0.018867925
47870 PROGRAMAÇÃO APLICADA 0.018518519

Relacionando as iniciações científicas com seus professores

Faz em Dataframe pela possibilidade de realizar merge

In [294]:
def relacionar_dados(professores, relacionado = ""):
    relacoes = []

    for professor in professores:
        siape = professor.get("siape")
        nome = professor.get("nome")

        trabalhos = professor.get(relacionado, [])

        for trabalho in trabalhos:
            relacoes.append({
                "professor_id": siape,
                "nome": nome,
                "objeto_id": trabalho
            })
            
    return pd.DataFrame(relacoes)

In [295]:
relacao_professor_ic = relacionar_dados(professores_dados, "trabalhosIniciacaoCientifica")

In [ ]:
relacao_professor_ic

   professor_id                              nome     objeto_id
0       2127183             BRUNO TARDIOLE KUEHNE  f001be6c8d33
1       2127183             BRUNO TARDIOLE KUEHNE  a0d1dae32993
2       2127183             BRUNO TARDIOLE KUEHNE  1fe0a29a59a3
3       1810770           DANILO HENRIQUE SPADOTI  6eb11d095a65
4       1810770           DANILO HENRIQUE SPADOTI  0af079870b1f
5       1810770           DANILO HENRIQUE SPADOTI  843757a0e743
6       1810770           DANILO HENRIQUE SPADOTI  f55732890b00
7       1810770           DANILO HENRIQUE SPADOTI  1904316495e5
8       1634986        EDVARD MARTINS DE OLIVEIRA  6d9b570e8513
9       1634986        EDVARD MARTINS DE OLIVEIRA  276846a8b564
10      1634986        EDVARD MARTINS DE OLIVEIRA  97244acbb82b
11      1634986        EDVARD MARTINS DE OLIVEIRA  6da28dc7ebaf
12      6394694           EGON LUIZ MULLER JUNIOR  efc40bb6e0cf
13      6394694           EGON LUIZ MULLER JUNIOR  61419ccaaeb8
14      6394694           EGON LUIZ MULLER JUNIOR  f8977f97857e
15      6394694           EGON LUIZ MULLER JUNIOR  25a15ebb4352
16      3150657  GABRIEL ANTONIO FANELLI DE SOUZA  09244b2f683a
17      3150657  GABRIEL ANTONIO FANELLI DE SOUZA  6f41befe0abb
18      3150657  GABRIEL ANTONIO FANELLI DE SOUZA  417eae0df1af
19      3150657  GABRIEL ANTONIO FANELLI DE SOUZA  90105b4346bd
20      3150657  GABRIEL ANTONIO FANELLI DE SOUZA  7998165825cc
21      3150657  GABRIEL ANTONIO FANELLI DE SOUZA  f9b7af541813
22      3150657  GABRIEL ANTONIO FANELLI DE SOUZA  a0a58a37076a
23      3150657  GABRIEL ANTONIO FANELLI DE SOUZA  80c9f1cbd437
24      2195502            GUSTAVO DELLA COLLETTA  93f7200d69d1
25      2195502            GUSTAVO DELLA COLLETTA  5304f7d672ed
26      2195502            GUSTAVO DELLA COLLETTA  f0890bd4eb6a
27      2195502            GUSTAVO DELLA COLLETTA  5f2d00c29d6e
28      2195502            GUSTAVO DELLA COLLETTA  618c08cdde4c
29      2642873    KLEBER ROBERTO DA SILVA SANTOS  ad87b6f82193
30      3288575                 RAMON MAIA BORGES  69b711d70b9a
31      3288575                 RAMON MAIA BORGES  869381cbbec4
32      2256795           ROBSON BAUWELZ GONZATTI  92d0c1e746e0
33      2256795           ROBSON BAUWELZ GONZATTI  d20805e76bba
34      2256795           ROBSON BAUWELZ GONZATTI  361a698ec178
35      2256795           ROBSON BAUWELZ GONZATTI  6b4f4e1d8380
36      2256795           ROBSON BAUWELZ GONZATTI  b4d5259e3843
37      2256795           ROBSON BAUWELZ GONZATTI  621e2ec802d8
38      2256795           ROBSON BAUWELZ GONZATTI  65cfdcfe4168
39      2256795           ROBSON BAUWELZ GONZATTI  9a0dbdc40add
40      3297076             WILSON CESAR SANT'ANA  8cab9b8a7b09
41      3297076             WILSON CESAR SANT'ANA  198d41e77b76
42      3297076             WILSON CESAR SANT'ANA  e5bd86f84b37
43      3297076             WILSON CESAR SANT'ANA  961b7f5bb2c7
44      3297076             WILSON CESAR SANT'ANA  bed1a275d998
45      3297076             WILSON CESAR SANT'ANA  89408719d345

In [297]:
def criar_dataframe_resultados_trabalhos(resultados_trabalhos):
    resultados = []

    for point in resultados_trabalhos:
        resultados.append({
            "objeto_id": str(point.payload["id"]),
            "score": point.score
        })

    return pd.DataFrame(resultados)

In [298]:
def associar_scores_a_professores(resultados_trabalhos,relacao):
    trabalhos_df = criar_dataframe_resultados_trabalhos(
        resultados_trabalhos
    )

    resultado = relacao.merge(
        trabalhos_df,
        on="objeto_id",
        how="inner"
    )

    return resultado.sort_values(
        by="score",
        ascending=False
    ).reset_index(drop=True)

Associar as iniciações científicas buscadas com os professores correspondentes

In [299]:
resultado_professor_trabalho_unico = associar_scores_a_professores(busca_realizada_ics, relacao_professor_ic)

In [300]:
associar_scores_a_professores(busca_realizada_ics, relacao_professor_ic)

   professor_id                              nome     objeto_id     score
0       1634986        EDVARD MARTINS DE OLIVEIRA  6d9b570e8513  0.416667
1       2195502            GUSTAVO DELLA COLLETTA  f0890bd4eb6a  0.325000
2       2256795           ROBSON BAUWELZ GONZATTI  92d0c1e746e0  0.210145
3       2127183             BRUNO TARDIOLE KUEHNE  f001be6c8d33  0.155556
4       3297076             WILSON CESAR SANT'ANA  198d41e77b76  0.133838
5       2642873    KLEBER ROBERTO DA SILVA SANTOS  ad87b6f82193  0.121795
6       2256795           ROBSON BAUWELZ GONZATTI  d20805e76bba  0.076316
7       3297076             WILSON CESAR SANT'ANA  e5bd86f84b37  0.071429
8       6394694           EGON LUIZ MULLER JUNIOR  efc40bb6e0cf  0.063508
9       2195502            GUSTAVO DELLA COLLETTA  618c08cdde4c  0.058824
10      6394694           EGON LUIZ MULLER JUNIOR  f8977f97857e  0.050000
11      1810770           DANILO HENRIQUE SPADOTI  6eb11d095a65  0.045455
12      3150657  GABRIEL ANTONIO FANELLI DE SOUZA  417eae0df1af  0.038462
13      1810770           DANILO HENRIQUE SPADOTI  f55732890b00  0.030303

Unir diferentes trabalhos de um mesmo professor 
- Pega os 3 com maiores scores e faz a média

In [301]:
def calcular_score_trabalhos(resultado):

    scores = (
        resultado
        .sort_values(
            by=["professor_id", "score"],
            ascending=[True, False]
        )
        .groupby("professor_id")
        .head(3)
        .groupby("professor_id")["score"]
        .mean()
        .reset_index()
        .rename(columns={
            "score": "work_score"
        })
    )

    return scores

In [ ]:
score_trabalhos_por_professor = calcular_score_trabalhos(resultado_professor_trabalho_unico)

In [303]:
calcular_score_trabalhos(resultado_professor_trabalho_unico)

  professor_id  work_score
0      1634986    0.416667
1      1810770    0.037879
2      2127183    0.155556
3      2195502    0.191912
4      2256795    0.143230
5      2642873    0.121795
6      3150657    0.038462
7      3297076    0.102633
8      6394694    0.056754

Score do perfil dos professores

In [111]:
def criar_dataframe_resultados_professores(resultados):
    dados = []

    for ponto in resultados:
        if not ponto.payload:
            continue

        dados.append({
            "professor_id": ponto.payload["id"],
            "professor_nome": ponto.payload["nome"],
            "professor_score": ponto.score
        })

    return pd.DataFrame(dados)

In [ ]:
scores_perfis_professores = (criar_dataframe_resultados_professores(busca_realizada_perfis_professores))

In [ ]:
criar_dataframe_resultados_professores(busca_realizada_perfis_professores)

   professor_id                           professor_nome  professor_score
0       1545021        CARLOS HENRIQUE VALERIO DE MORAES         0.625000
1       1682528         THATYANA DE FARIA PIOLA SERAPHIM         0.547619
2       1967206                          LUCIANO BERTINI         0.500000
3       1732597     RODRIGO MAXIMIANO ANTUNES DE ALMEIDA         0.476191
4       1374755            DECIO RENNO DE MENDONCA FARIA         0.350000
5       3529390                   BRENO DE OLIVEIRA RENO         0.312500
6        394747                     LUIZ EDIVAL DE SOUZA         0.255556
7        394714              JOSE ALBERTO FERREIRA FILHO         0.238095
8       3443612                  BARBARA PIMENTA CAETANO         0.226190
9       1097837            GABRIEL CIRAC MENDES DE SOUZA         0.200000
10      1543328                            ENZO SERAPHIM         0.162500
11       395119                     TALES CLEBER PIMENTA         0.157258
12      1457656                   EDMILSON MARMO MOREIRA         0.152778
13      2195171                       ROBSON LUIZ MORENO         0.150000
14      2642873           KLEBER ROBERTO DA SILVA SANTOS         0.139683
15      2019312                 ODILON DE OLIVEIRA DUTRA         0.132479
16      3150657         GABRIEL ANTONIO FANELLI DE SOUZA         0.126923
17      1999579          JOAO PAULO REUS RODRIGUES LEITE         0.124242
18      1862488                 JEREMIAS BARBOSA MACHADO         0.124060
19      6394694                  EGON LUIZ MULLER JUNIOR         0.119481
20      1310498                           ANDRE BERNARDI         0.116667
21      1560417       LUIS HENRIQUE DE CARVALHO FERREIRA         0.098824
22      1666035              LEONARDO BRESEGHELLO ZOCCAL         0.094538
23      1887447                  CAIO FERNANDES DE PAULA         0.083882
24      3104470             LUIZ LENARTH GABRIEL VERMAAS         0.078704
25      1634986               EDVARD MARTINS DE OLIVEIRA         0.077961
26      2269653  MATEUS AUGUSTO FAUSTINO CHAIB JUNQUEIRA         0.074646
27      2372188                GUILHERME DE SOUSA BASTOS         0.072890
28      2127183                    BRUNO TARDIOLE KUEHNE         0.072482
29       394764                MAURILIO PEREIRA COUTINHO         0.072258
30      3525710               RODRIGO DE PAULA RODRIGUES         0.069264
31      2256795                  ROBSON BAUWELZ GONZATTI         0.067873
32      1814241              RONDINELI RODRIGUES PEREIRA         0.064583
33      2234207      ANA PAULA SIQUEIRA SILVA DE ALMEIDA         0.062852
34      1795095                 CARLOS WALDECIR DE SOUZA         0.062261
35      2576624        GISCARD FRANCIMEIRE CINTRA VELOSO         0.060293
36      2230762         FERNANDO HENRIQUE DUARTE GUARACY         0.058442
37      3297076                    WILSON CESAR SANT'ANA         0.056619
38      3524775                  JUAN PABLO OCHOA AVILES         0.055944
39      3288575                        RAMON MAIA BORGES         0.052168
40      1810770                  DANILO HENRIQUE SPADOTI         0.050000
41      1062611                     ENIO ROBERTO RIBEIRO         0.049572
42      2195502                   GUSTAVO DELLA COLLETTA         0.049451

Unir disciplinas e professores

In [343]:
relacao_professor_disciplina = relacionar_dados(professores_dados, "disciplinasSigaa")

In [344]:
relacao_professor_disciplina

     professor_id                                 nome objeto_id
0         2234207  ANA PAULA SIQUEIRA SILVA DE ALMEIDA       175
1         2234207  ANA PAULA SIQUEIRA SILVA DE ALMEIDA     29953
2         2234207  ANA PAULA SIQUEIRA SILVA DE ALMEIDA     45429
3         2234207  ANA PAULA SIQUEIRA SILVA DE ALMEIDA     46570
4         2234207  ANA PAULA SIQUEIRA SILVA DE ALMEIDA     46576
...           ...                                  ...       ...
1431      3297076                WILSON CESAR SANT'ANA     46928
1432      3297076                WILSON CESAR SANT'ANA     46960
1433      3297076                WILSON CESAR SANT'ANA      5671
1434      3297076                WILSON CESAR SANT'ANA      5693
1435      3297076                WILSON CESAR SANT'ANA      5850

[1436 rows x 3 columns]

In [345]:
resultado_professor_disciplina = associar_scores_a_professores(busca_realizada_disciplinas, relacao_professor_disciplina)

In [346]:
resultado_professor_disciplina

    professor_id                                  nome objeto_id     score
0        1732597  RODRIGO MAXIMIANO ANTUNES DE ALMEIDA      5651  0.750000
1        1374755         DECIO RENNO DE MENDONCA FARIA      5300  0.625000
2        1545021     CARLOS HENRIQUE VALERIO DE MORAES      5300  0.625000
3        1967206                       LUCIANO BERTINI      5300  0.625000
4        1732597  RODRIGO MAXIMIANO ANTUNES DE ALMEIDA      5300  0.625000
..           ...                                   ...       ...       ...
110      1457656                EDMILSON MARMO MOREIRA     29660  0.019231
111      1310498                        ANDRE BERNARDI      5296  0.019231
112      1457656                EDMILSON MARMO MOREIRA     29510  0.018868
113      1999579       JOAO PAULO REUS RODRIGUES LEITE     29510  0.018868
114      1310498                        ANDRE BERNARDI     47870  0.018519

[115 rows x 4 columns]

In [305]:
def calcular_score_disciplinas(resultado):

    scores = (
        resultado
        .sort_values(
            by=["professor_id", "score"],
            ascending=[True, False]
        )
        .groupby("professor_id")
        .head(3)
        .groupby("professor_id")["score"]
        .mean()
        .reset_index()
        .rename(columns={
            "score": "disciplina_score"
        })
    )

    return scores

In [347]:
score_disciplinas = calcular_score_disciplinas(resultado_professor_disciplina)

In [348]:
score_disciplinas

   professor_id  disciplina_score
0       1062611          0.037319
1       1097837          0.324128
2       1310498          0.087288
3       1374755          0.550595
4       1457656          0.041806
5       1543328          0.072437
6       1545021          0.404101
7       1560417          0.236111
8       1634986          0.023256
9       1666035          0.025641
10      1682528          0.043478
11      1732597          0.617063
12      1967206          0.550595
13      1999579          0.058774
14      2019312          0.034582
15      2127183          0.050089
16      2195171          0.030678
17      2195502          0.028068
18      2372188          0.051988
19      2576624          0.034560
20      2642873          0.027983
21      3104470          0.033157
22      3443612          0.027778
23      3525710          0.097223
24       394714          0.039568
25       394747          0.026035
26       394764          0.069304
27       395119          0.071673

Junção dos scores obtidos

In [ ]:
def combinar_scores(
    scores_trabalhos,
    scores_professores,
    scores_disciplinas,
    peso_trabalhos=0.5,
    peso_professor=0.2,
    peso_disciplinas=0.3
):
    resultado = (
        scores_trabalhos
        .merge(
            scores_professores,
            on="professor_id",
            how="outer"
        )
        .merge(
            scores_disciplinas,
            on="professor_id",
            how="outer"
        )
    )

    resultado["work_score"] = (
        resultado["work_score"].fillna(0)
    )

    resultado["professor_score"] = (
        resultado["professor_score"].fillna(0)
    )

    resultado["disciplina_score"] = (
        resultado["disciplina_score"].fillna(0)
    )

    resultado["score_final"] = (
        peso_trabalhos * resultado["work_score"]
        +
        peso_professor * resultado["professor_score"]
        +
        peso_disciplinas * resultado["disciplina_score"]
    )

    return resultado.sort_values(
        "score_final",
        ascending=False
    )

In [350]:
score_final_professores = combinar_scores(score_trabalhos_por_professor,scores_perfis_professores,score_disciplinas)

In [351]:
combinar_scores(score_trabalhos_por_professor,scores_perfis_professores,score_disciplinas)

,professor_id,work_score,professor_nome,professor_score,disciplina_score,score_final
11,1732597,0.000000,RODRIGO MAXIMIANO ANTUNES DE ALMEIDA,0.476191,0.617063,0.280357
17,1967206,0.000000,LUCIANO BERTINI,0.500000,0.550595,0.265179
6,1545021,0.000000,CARLOS HENRIQUE VALERIO DE MORAES,0.625000,0.404101,0.246230
3,1374755,0.000000,DECIO RENNO DE MENDONCA FARIA,0.350000,0.550595,0.235179
8,1634986,0.416667,EDVARD MARTINS DE OLIVEIRA,0.077961,0.023256,0.230902
1,1097837,0.000000,GABRIEL CIRAC MENDES DE SOUZA,0.200000,0.324128,0.137238
10,1682528,0.000000,THATYANA DE FARIA PIOLA SERAPHIM,0.547619,0.043478,0.122567
22,2195502,0.191912,GUSTAVO DELLA COLLETTA,0.049451,0.028068,0.114266
20,2127183,0.155556,BRUNO TARDIOLE KUEHNE,0.072482,0.050089,0.107301
29,2642873,0.121795,KLEBER ROBERTO DA SILVA SANTOS,0.139683,0.027983,0.097229
7,1560417,0.000000,LUIS HENRIQUE DE CARVALHO FERREIRA,0.098824,0.236111,0.090598
25,2256795,0.143230,ROBSON BAUWELZ GONZATTI,0.067873,0.000000,0.085190
33,3297076,0.102633,WILSON CESAR SANT'ANA,0.056619,0.000000,0.062641
37,3529390,0.000000,BRENO DE OLIVEIRA RENO,0.312500,0.000000,0.062500
38,394714,0.000000,JOSE ALBERTO FERREIRA FILHO,0.238095,0.039568,0.059490
39,394747,0.000000,LUIZ EDIVAL DE SOUZA,0.255556,0.026035,0.058922
5,1543328,0.000000,ENZO SERAPHIM,0.162500,0.072437,0.054231
34,3443612,0.000000,BARBARA PIMENTA CAETANO,0.226190,0.027778,0.053571
41,395119,0.000000,TALES CLEBER PIMENTA,0.157258,0.071673,0.052953
42,6394694,0.056754,EGON LUIZ MULLER JUNIOR,0.119481,0.000000,0.052273
2,1310498,0.000000,ANDRE BERNARDI,0.116667,0.087288,0.049520
31,3150657,0.038462,GABRIEL ANTONIO FANELLI DE SOUZA,0.126923,0.000000,0.044615
4,1457656,0.000000,EDMILSON MARMO MOREIRA,0.152778,0.041806,0.043097
36,3525710,0.000000,RODRIGO DE PAULA RODRIGUES,0.069264,0.097223,0.043020
18,1999579,0.000000,JOAO PAULO REUS RODRIGUES LEITE,0.124242,0.058774,0.042481
21,2195171,0.000000,ROBSON LUIZ MORENO,0.150000,0.030678,0.039203
19,2019312,0.000000,ODILON DE OLIVEIRA DUTRA,0.132479,0.034582,0.036870
40,394764,0.000000,MAURILIO PEREIRA COUTINHO,0.072258,0.069304,0.035243
27,2372188,0.000000,GUILHERME DE SOUSA BASTOS,0.072890,0.051988,0.030175
13,1810770,0.037879,DANILO HENRIQUE SPADOTI,0.050000,0.000000,0.028939
9,1666035,0.000000,LEONARDO BRESEGHELLO ZOCCAL,0.094538,0.025641,0.026600
30,3104470,0.000000,LUIZ LENARTH GABRIEL VERMAAS,0.078704,0.033157,0.025688
15,1862488,0.000000,JEREMIAS BARBOSA MACHADO,0.124060,0.000000,0.024812
28,2576624,0.000000,GISCARD FRANCIMEIRE CINTRA VELOSO,0.060293,0.034560,0.022426
0,1062611,0.000000,ENIO ROBERTO RIBEIRO,0.049572,0.037319,0.021110
16,1887447,0.000000,CAIO FERNANDES DE PAULA,0.083882,0.000000,0.016776
26,2269653,0.000000,MATEUS AUGUSTO FAUSTINO CHAIB JUNQUEIRA,0.074646,0.000000,0.014929
14,1814241,0.000000,RONDINELI RODRIGUES PEREIRA,0.064583,0.000000,0.012917
24,2234207,0.000000,ANA PAULA SIQUEIRA SILVA DE ALMEIDA,0.062852,0.000000,0.012570
12,1795095,0.000000,CARLOS WALDECIR DE SOUZA,0.062261,0.000000,0.012452
23,2230762,0.000000,FERNANDO HENRIQUE DUARTE GUARACY,0.058442,0.000000,0.011688
35,3524775,0.000000,JUAN PABLO OCHOA AVILES,0.055944,0.000000,0.011189
32,3288575,0.000000,RAMON MAIA BORGES,0.052168,0.000000,0.010434

Busca Densa

In [ ]:
def busca_densa (embedding_aluno, collection ="", limit = 10):
    results = client_qdrant.query_points(
        collection,
        query=embedding_aluno,
        using="dense",
        limit=limit,
    )
    return results

resultado_densa_perfil = busca_densa(embedding_aluno)
resultado_densa_disciplinas = busca_densa(embedding_aluno)
resultado_densa_ics = busca_densa(embedding_aluno)

In [ ]:
ranking_densa = []
for point in resultado_densa.points:
    print(point.payload["nome"], point.score)
    
    ranking_densa.append(point.payload["nome"], point.score)

Reranking

In [352]:
FINAL_PROFESSOR_K = 15
candidatos_reranking = score_final_professores.head(FINAL_PROFESSOR_K)

In [488]:
candidatos_reranking

,professor_id,work_score,professor_nome,professor_score,disciplina_score,score_final
11,1732597,0.000000,RODRIGO MAXIMIANO ANTUNES DE ALMEIDA,0.476191,0.617063,0.280357
17,1967206,0.000000,LUCIANO BERTINI,0.500000,0.550595,0.265179
6,1545021,0.000000,CARLOS HENRIQUE VALERIO DE MORAES,0.625000,0.404101,0.246230
3,1374755,0.000000,DECIO RENNO DE MENDONCA FARIA,0.350000,0.550595,0.235179
8,1634986,0.416667,EDVARD MARTINS DE OLIVEIRA,0.077961,0.023256,0.230902
1,1097837,0.000000,GABRIEL CIRAC MENDES DE SOUZA,0.200000,0.324128,0.137238
10,1682528,0.000000,THATYANA DE FARIA PIOLA SERAPHIM,0.547619,0.043478,0.122567
22,2195502,0.191912,GUSTAVO DELLA COLLETTA,0.049451,0.028068,0.114266
20,2127183,0.155556,BRUNO TARDIOLE KUEHNE,0.072482,0.050089,0.107301
29,2642873,0.121795,KLEBER ROBERTO DA SILVA SANTOS,0.139683,0.027983,0.097229
7,1560417,0.000000,LUIS HENRIQUE DE CARVALHO FERREIRA,0.098824,0.236111,0.090598
25,2256795,0.143230,ROBSON BAUWELZ GONZATTI,0.067873,0.000000,0.085190
33,3297076,0.102633,WILSON CESAR SANT'ANA,0.056619,0.000000,0.062641
37,3529390,0.000000,BRENO DE OLIVEIRA RENO,0.312500,0.000000,0.062500
38,394714,0.000000,JOSE ALBERTO FERREIRA FILHO,0.238095,0.039568,0.059490

In [ ]:
def criar_candidatos_reranking(
    ranking,
    professores_dados,
    relacao_professor_trabalho,
    trabalhos_por_id,
    relacao_professor_disciplina,
    disciplinas_por_id,
    n_trabalhos=3,
    n_disciplinas=3
):

    candidatos = []

    # Obter professores pelo siape

    professores_por_id = {
        str(professor["siape"]): professor
        for professor in professores_dados
    }

    for _, candidato in ranking.iterrows():

        professor_id = str(candidato["professor_id"])

        #  busca a informação do perfil do professor

        perfil = professores_por_id.get(professor_id)

        if perfil is None:
            continue

        texto_perfil = montar_texto_perfil_professor(perfil)

        # busca informação dos trabalhos

        trabalhos_do_professor = (
            relacao_professor_trabalho[
                relacao_professor_trabalho["professor_id"].astype(str)
                == professor_id
            ]
            .sort_values("score", ascending=False)
            .head(n_trabalhos)
        )

        textos_trabalhos = []
        trabalhos_reranking = []

        for _, relacao in trabalhos_do_professor.iterrows():

            trabalho_id = str(relacao["objeto_id"])

            trabalho = trabalhos_por_id.get(trabalho_id)

            if trabalho is None:
                continue

            texto_trabalho = trabalho.get("texto_embedding")

            if texto_trabalho:
                textos_trabalhos.append(texto_trabalho)

            trabalhos_reranking.append({
                "trabalho_id": trabalho_id,
                "titulo": trabalho.get("metadata", {}).get("titulo"),
                "texto": texto_trabalho,
                "score": relacao.get("score")
            })

        # busca informações das disciplinas
        disciplinas_do_professor = (
            relacao_professor_disciplina[
                relacao_professor_disciplina["professor_id"].astype(str)
                == professor_id
            ]
            .sort_values("score", ascending=False)
            .head(n_disciplinas)
        )

        textos_disciplinas = []
        disciplinas_reranking = []

        for _, relacao in disciplinas_do_professor.iterrows():

            disciplina_id = str(relacao["objeto_id"])

            disciplina = disciplinas_por_id.get(disciplina_id)

            if disciplina is None:
                continue

            texto_disciplina = disciplina.get("texto_embedding")

            if texto_disciplina:
                textos_disciplinas.append(texto_disciplina)

            disciplinas_reranking.append({
                "disciplina_id": disciplina_id,
                "nome": disciplina.get("metadata", {}).get("nome"),
                "texto": texto_disciplina,
                "score": relacao.get("score")
            })

        texto_reranking = texto_perfil

        if textos_trabalhos:
            texto_reranking += (
                "\n\nTrabalhos relevantes:\n"
                + "\n\n".join(textos_trabalhos)
            )

        if textos_disciplinas:
            texto_reranking += (
                "\n\nDisciplinas relevantes:\n"
                + "\n\n".join(textos_disciplinas)
            )


        candidatos.append({
            "professor_id": professor_id,
            "professor_nome": candidato["professor_nome"],

            # Scores
            "work_score": candidato["work_score"],
            "professor_score": candidato["professor_score"],
            "disciplina_score": candidato["disciplina_score"],
            "score_final": candidato["score_final"],

            "texto_perfil": texto_perfil,
            "texto_reranking": texto_reranking,

            "trabalhos_relevantes": trabalhos_reranking,

            "disciplinas_relevantes": disciplinas_reranking
        })

    return candidatos

In [363]:
trabalhos_por_id = {
    str(trabalho["id"]): trabalho
    for trabalho in ics_perfis_busca
}

In [364]:
disciplina_por_id = {
    str(trabalho["id"]): trabalho
    for trabalho in disciplinas_perfil_busca
}

In [490]:
professores_para_reranking = criar_candidatos_reranking(candidatos_reranking, professores_dados,resultado_professor_trabalho_unico,trabalhos_por_id,resultado_professor_disciplina,disciplina_por_id)

In [491]:
professores_para_reranking

[{'professor_id': '1732597',
  'professor_nome': 'RODRIGO MAXIMIANO ANTUNES DE ALMEIDA',
  'work_score': 0.0,
  'professor_score': 0.4761905,
  'disciplina_score': 0.6170635,
  'score_final': 0.28035715,
  'texto_perfil': 'Resumo: Possui graduação em Engenharia de Controle e Automação pela Universidade Federal de Itajubá (2007), mestrado em Engenharia Elétrica pela Universidade Federal de Itajubá (2009) e doutorado em Engenharia Elétrica pela Universidade Federal de Itajubá (2013). Atualmente é professor adjunto da Universidade Federal de Itajubá. Leciona nas áreas de eletrônica, interface e periféricos, sistemas embarcados e sistemas operacionais. Suas pesquisas incluem tópicos sobre desenvolvimento de hardware, RTOS, segurança e usabilidade de sistemas eletrônicos. Trabalha em projetos de sistemas críticos onde confiabilidade e estabilidade são requisitos, seja do ponto de vista do sistema ou da interação do usuário com o equipamento\nFormação Profissional Acadêmica: Engenheiro de Controle e Automação, Mestrado e Doutorado em Engenharia Eletrica\nÁreas de Interesse: Sistemas embarcados, eletrônica, ensino de engenharia\nÁreas de conhecimento:\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Metodologia e Técnicas da Computação. Especialidade: Sistemas Embarcados\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Sistemas de Computação. Especialidade: Arquitetura de Sistemas de Computação\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Sistemas de Computação. Especialidade: Hardware\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Eletrônica Industrial, Sistemas e Controles Eletrônicos. Especialidade: Controle de Processos Eletrônicos, Retroalimentação\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Medidas Elétricas, Magnéticas e Eletrônicas; Instrumentação. Especialidade: Sistemas Eletrônicos de Medida e de Controle\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Metodologia e Técnicas da Computação. Especialidade: Engenharia de Software\n\nLinhas de pesquisa: Filtros digitais, Desenvolvimento de Firmware, Biosensores e estimuladores elétricos, Sistemas microcontrolados, Sistemas Embarcados, Sistemas Operacionais de Tempo Real, Usabilidade, Desenvolvimento de Firmware, Filtros Digitais, Ensino de Engenharia\n\nPalavras-chave: Sistemas Embarcados, Segurança, Rede neural artificial, Classificação de padrões',
  'texto_reranking': 'Resumo: Possui graduação em Engenharia de Controle e Automação pela Universidade Federal de Itajubá (2007), mestrado em Engenharia Elétrica pela Universidade Federal de Itajubá (2009) e doutorado em Engenharia Elétrica pela Universidade Federal de Itajubá (2013). Atualmente é professor adjunto da Universidade Federal de Itajubá. Leciona nas áreas de eletrônica, interface e periféricos, sistemas embarcados e sistemas operacionais. Suas pesquisas incluem tópicos sobre desenvolvimento de hardware, RTOS, segurança e usabilidade de sistemas eletrônicos. Trabalha em projetos de sistemas críticos onde confiabilidade e estabilidade são requisitos, seja do ponto de vista do sistema ou da interação do usuário com o equipamento\nFormação Profissional Acadêmica: Engenheiro de Controle e Automação, Mestrado e Doutorado em Engenharia Eletrica\nÁreas de Interesse: Sistemas embarcados, eletrônica, ensino de engenharia\nÁreas de conhecimento:\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Metodologia e Técnicas da Computação. Especialidade: Sistemas Embarcados\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Sistemas de Computação. Especialidade: Arquitetura de Sistemas de Computação\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Sistemas de Computação. Especialidade: Hardware\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Eletrônica Industrial, Sistemas e Controles Eletrônicos. Especialidade: Controle de Processos Eletrônicos, Retroalimentação\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Medidas Elétricas, Magnéticas e Eletrônicas; Instrumentação. Especialidade: Sistemas Eletrônicos de Medida e de Controle\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Metodologia e Técnicas da Computação. Especialidade: Engenharia de Software\n\nLinhas de pesquisa: Filtros digitais, Desenvolvimento de Firmware, Biosensores e estimuladores elétricos, Sistemas microcontrolados, Sistemas Embarcados, Sistemas Operacionais de Tempo Real, Usabilidade, Desenvolvimento de Firmware, Filtros Digitais, Ensino de Engenharia\n\nPalavras-chave: Sistemas Embarcados, Segurança, Rede neural artificial, Classificação de padrões\n\nDisciplinas relevantes:\nNome: PROGRAMAÇÃO PARA SISTEMAS EMBARCADOS\nEmenta: conceitos gerais de computação embarcada. programação de sistemas embarcados utilizando linguagem c. tipos de dados e operações com bits. diretivas de compilação e pré-compilação. utilização de periféricos. multiplexação de entradas e saídas. interrupções. organização e arquitetura de programas para sistemas embarcados. limitações de sistemas embarcados.\n\nNome: LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.\n\nNome: PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
  'trabalhos_relevantes': [],
  'disciplinas_relevantes': [{'disciplina_id': '5651',
    'nome': 'PROGRAMAÇÃO PARA SISTEMAS EMBARCADOS',
    'texto': 'Nome: PROGRAMAÇÃO PARA SISTEMAS EMBARCADOS\nEmenta: conceitos gerais de computação embarcada. programação de sistemas embarcados utilizando linguagem c. tipos de dados e operações com bits. diretivas de compilação e pré-compilação. utilização de periféricos. multiplexação de entradas e saídas. interrupções. organização e arquitetura de programas para sistemas embarcados. limitações de sistemas embarcados.',
    'score': 0.75},
   {'disciplina_id': '5300',
    'nome': 'LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA',
    'texto': 'Nome: LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
    'score': 0.625},
   {'disciplina_id': '5295',
    'nome': 'PROGRAMAÇÃO EMBARCADA',
    'texto': 'Nome: PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
    'score': 0.4761905}]},
 {'professor_id': '1967206',
  'professor_nome': 'LUCIANO BERTINI',
  'work_score': 0.0,
  'professor_score': 0.5,
  'disciplina_score': 0.55059525,
  'score_final': 0.26517857499999997,
  'texto_perfil': 'Resumo: Graduou-se em Engenharia Elétrica (1995) pela Universidade Federal de Itajubá (UNIFEI). Concluiu mestrado em Engenharia Elétrica na área de Controle, Automação e Microinformática (1998), pela Universidade Federal de Santa Catarina (UFSC) e doutorado em Computação (2009) pela Universidade Federal Fluminense (UFF), na área de Sistemas Paralelos e Distribuídos. Realizou um ano de pesquisas, em doutorado sanduíche, na Universidade de Pittsburgh, EUA, no laboratório Power-Aware Real-Time Systems. Atuou como engenheiro eletrônico de sistemas embarcados para a empresa Di-elétrons Ltda em Belo Horizonte - MG, de 1999 a 2003. Foi professor de Introdução à Computação e Circuitos Eletro-Eletrônicos na UFRJ, campus de Macaé (temporário 20h nível Adjunto). Foi também engenheiro eletrônico de controle e automação da PETROBRAS em Macaé/RJ entre 2008 e 2014. Tem experiência docente em arquitetura de computadores, circuitos digitais e analógicos, sistemas embarcados, técnicas de programação em C, estruturas de dados e análise de algoritmos. De 2014 a 2022 foi professor Adjunto no Departamento de Computação (RCM) da UFF em Rio das Ostras/RJ, lecionando Circuitos Digitais, Laboratório de Circuitos Digitais e Arquitetura de Computadores. Desde 2022 é professor no Instituto de Engenharia de Sistemas e Tecnologia da informação (IESTI) da UNIFEI na área de sistemas embarcados. Tem interesse em temas de pesquisa relacionados a sistemas embarcados e aplicações com FPGA, Internet das Coisas e controle inteligente de processos industriais\nFormação Profissional Acadêmica: Técnico em eletrônica (1989), engenheiro eletrônico EFEI (1995), mestre em engenharia elétrica UFSC (1998) e doutor em ciência da computação UFF (2009)\nÁreas de Interesse: circuitos digitais, arquitetura de computadores, sistemas embarcados, algoritmos\nÁreas de conhecimento:\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Sistemas de Computação. Especialidade: Arquitetura de Sistemas de Computação\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Circuitos Digitais\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Teoria da Computação. Especialidade: Análise de Algoritmos e Complexidade de Computação\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Sistemas Eficientes Em Energia\n\nLinhas de pesquisa: sistemas embarcados, Internet das Coisas, controle de processos, sistemas digitais\n\nPalavras-chave: Computação Eficiente em Energia, Sistemas de tempo real, Computação Paralela e Distribuída, Clusters de Servidores, Servidores Web, Escalonamento com Otimização da Potência, Sistemas Distribuídos, Sistemas Multimídia Interativos, Padrão CORBA, Padrão MHEG-5, DSMCC e DAVIC',
  'texto_reranking': 'Resumo: Graduou-se em Engenharia Elétrica (1995) pela Universidade Federal de Itajubá (UNIFEI). Concluiu mestrado em Engenharia Elétrica na área de Controle, Automação e Microinformática (1998), pela Universidade Federal de Santa Catarina (UFSC) e doutorado em Computação (2009) pela Universidade Federal Fluminense (UFF), na área de Sistemas Paralelos e Distribuídos. Realizou um ano de pesquisas, em doutorado sanduíche, na Universidade de Pittsburgh, EUA, no laboratório Power-Aware Real-Time Systems. Atuou como engenheiro eletrônico de sistemas embarcados para a empresa Di-elétrons Ltda em Belo Horizonte - MG, de 1999 a 2003. Foi professor de Introdução à Computação e Circuitos Eletro-Eletrônicos na UFRJ, campus de Macaé (temporário 20h nível Adjunto). Foi também engenheiro eletrônico de controle e automação da PETROBRAS em Macaé/RJ entre 2008 e 2014. Tem experiência docente em arquitetura de computadores, circuitos digitais e analógicos, sistemas embarcados, técnicas de programação em C, estruturas de dados e análise de algoritmos. De 2014 a 2022 foi professor Adjunto no Departamento de Computação (RCM) da UFF em Rio das Ostras/RJ, lecionando Circuitos Digitais, Laboratório de Circuitos Digitais e Arquitetura de Computadores. Desde 2022 é professor no Instituto de Engenharia de Sistemas e Tecnologia da informação (IESTI) da UNIFEI na área de sistemas embarcados. Tem interesse em temas de pesquisa relacionados a sistemas embarcados e aplicações com FPGA, Internet das Coisas e controle inteligente de processos industriais\nFormação Profissional Acadêmica: Técnico em eletrônica (1989), engenheiro eletrônico EFEI (1995), mestre em engenharia elétrica UFSC (1998) e doutor em ciência da computação UFF (2009)\nÁreas de Interesse: circuitos digitais, arquitetura de computadores, sistemas embarcados, algoritmos\nÁreas de conhecimento:\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Sistemas de Computação. Especialidade: Arquitetura de Sistemas de Computação\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Circuitos Digitais\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Teoria da Computação. Especialidade: Análise de Algoritmos e Complexidade de Computação\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Sistemas Eficientes Em Energia\n\nLinhas de pesquisa: sistemas embarcados, Internet das Coisas, controle de processos, sistemas digitais\n\nPalavras-chave: Computação Eficiente em Energia, Sistemas de tempo real, Computação Paralela e Distribuída, Clusters de Servidores, Servidores Web, Escalonamento com Otimização da Potência, Sistemas Distribuídos, Sistemas Multimídia Interativos, Padrão CORBA, Padrão MHEG-5, DSMCC e DAVIC\n\nDisciplinas relevantes:\nNome: LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.\n\nNome: PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
  'trabalhos_relevantes': [],
  'disciplinas_relevantes': [{'disciplina_id': '5300',
    'nome': 'LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA',
    'texto': 'Nome: LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
    'score': 0.625},
   {'disciplina_id': '5295',
    'nome': 'PROGRAMAÇÃO EMBARCADA',
    'texto': 'Nome: PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
    'score': 0.4761905}]},
 {'professor_id': '1545021',
  'professor_nome': 'CARLOS HENRIQUE VALERIO DE MORAES',
  'work_score': 0.0,
  'professor_score': 0.625,
  'disciplina_score': 0.4041005366666666,
  'score_final': 0.24623016099999998,
  'texto_perfil': 'Resumo: Possui graduação em Engenharia Elétrica pela Universidade Federal de Itajubá (2001), mestrado em Engenharia Elétrica pela Universidade Federal de Itajubá (2002) e doutorado em Engenharia Elétrica pela Universidade Federal de Itajubá (2006). Atualmente é professor associado 4 da Universidade Federal de Itajubá. Tem experiência na área de Engenharia Elétrica, com ênfase em Automação Eletrônica de Processos Elétricos e Industriais, atuando principalmente nos seguintes temas: inteligência artificial, sistemas elétricos, sistema especialista, controle inteligente e planejamento inteligente\nFormação Profissional Acadêmica: 1996 - Técnico de Eletrônica na ETEFMC; 2001 - Engenheiro Eletricista com Ênfase em Eletrotécnica na EFEI; 2002 - Mestre em Engenharia Elétrica na UNIFEI; 2006 - Doutor em Engenharia Elétrica na UNIFEI.\nÁreas de Interesse: SmartGrid, sistemas embarcados inteligentes, planejamento inteligente, veículos autônomos e engenharia biomédica.\nÁreas de conhecimento:\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Eletrônica Industrial, Sistemas e Controles Eletrônicos. Especialidade: Automação Eletrônica de Processos Elétricos e Industriais\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Computação\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Medidas Elétricas, Magnéticas e Eletrônicas; Instrumentação. Especialidade: Instrumentação Eletrônica\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Eletrônica Industrial, Sistemas e Controles Eletrônicos. Especialidade: Eletrônica Industrial\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Eletrônica Industrial, Sistemas e Controles Eletrônicos. Especialidade: Controle de Processos Eletrônicos, Retroalimentação\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Sistemas Elétricos de Potência. Especialidade: Transmissão da Energia Elétrica, Distribuição da Energia Elétrica\n\nLinhas de pesquisa: Aplicação de Sistemas Inteligentes em Dispositivos Móveis, Aplicação de Sistemas Inteligentes em Sistemas Embarcados, Aplicação de Sistemas Inteligentes na Engenharia de Controle e Automação, Formulação de Modelos Matemáticos para a Engenharia de Controle e Automação, Desenvolvimento e Aplicação de Lógicas Não-Clássicas, Desenvolvimento de Conceitos Teóricos em Inteligência Aritificial, Visão Computacional e Técnicas Avançadas de Reconhecimento de Padrões\n\nPalavras-chave: Agentes Inteligente, Inteligência Artificial, Sistema Elétrico, Mineração de Dados, Transformação da Classe de Tensão, Sistemas Elétricos, Análise Técnico-Econômica',

Reranking (com a mesma lógica da busca cada conteúdo e rankeado e depois ligado a seu professor correspondente)

In [384]:
reranker = FlagReranker('BAAI/bge-reranker-v2-m3', use_fp16=True, normalize=True)

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

In [493]:
def criar_candidatos_reranking_v2(
    ranking,
    professores_dados,
    relacao_professor_trabalho,
    trabalhos_por_id,
    relacao_professor_disciplina,
    disciplinas_por_id,
    n_trabalhos=3,
    n_disciplinas=3
):

    candidatos = []

    # -----------------------------------
    # 1. Indexar professores pelo SIAPE
    # -----------------------------------

    professores_por_id = {
        str(professor["siape"]): professor
        for professor in professores_dados
    }

    # -----------------------------------
    # 2. Percorrer professores do ranking
    # -----------------------------------

    for _, candidato in ranking.iterrows():

        professor_id = str(candidato["professor_id"])

        perfil = professores_por_id.get(professor_id)

        if perfil is None:
            continue

        # -----------------------------------
        # 3. Perfil do professor
        # -----------------------------------

        texto_perfil = montar_texto_perfil_professor(perfil)

        if texto_perfil:

            candidatos.append({
                "professor_id": professor_id,
                "tipo": "professor",
                "item_id": professor_id,

                "texto": texto_perfil,

                "score_retrieval": candidato["professor_score"]
            })

        # -----------------------------------
        # 4. Trabalhos do professor
        # -----------------------------------

        trabalhos_do_professor = (
            relacao_professor_trabalho[
                relacao_professor_trabalho["professor_id"].astype(str)
                == professor_id
            ]
            .sort_values("score", ascending=False)
            .head(n_trabalhos)
        )

        for _, relacao in trabalhos_do_professor.iterrows():

            trabalho_id = str(relacao["objeto_id"])

            trabalho = trabalhos_por_id.get(trabalho_id)

            if trabalho is None:
                continue

            texto_trabalho = trabalho.get("texto_embedding")

            if not texto_trabalho:
                continue

            candidatos.append({
                "professor_id": professor_id,
                "tipo": "trabalho",
                "item_id": trabalho_id,

                "texto": texto_trabalho,

                "titulo": trabalho.get(
                    "metadata", {}
                ).get("titulo"),

                "score_retrieval": relacao["score"]
            })

        # -----------------------------------
        # 5. Disciplinas do professor
        # -----------------------------------

        disciplinas_do_professor = (
            relacao_professor_disciplina[
                relacao_professor_disciplina["professor_id"].astype(str)
                == professor_id
            ]
            .sort_values("score", ascending=False)
            .head(n_disciplinas)
        )

        for _, relacao in disciplinas_do_professor.iterrows():

            disciplina_id = str(relacao["objeto_id"])

            disciplina = disciplinas_por_id.get(
                disciplina_id
            )

            if disciplina is None:
                continue

            texto_disciplina = disciplina.get(
                "texto_embedding"
            )

            if not texto_disciplina:
                continue

            candidatos.append({
                "professor_id": professor_id,
                "tipo": "disciplina",
                "item_id": disciplina_id,

                "texto": texto_disciplina,

                "nome": disciplina.get(
                    "metadata", {}
                ).get("nome"),

                "score_retrieval": relacao["score"]
            })

    return candidatos

In [497]:
conteudo_reranking = criar_candidatos_reranking_v2(candidatos_reranking, professores_dados,resultado_professor_trabalho_unico,trabalhos_por_id,resultado_professor_disciplina,disciplina_por_id)

In [498]:
conteudo_reranking

[{'professor_id': '1732597',
  'tipo': 'professor',
  'item_id': '1732597',
  'texto': 'Resumo: Possui graduação em Engenharia de Controle e Automação pela Universidade Federal de Itajubá (2007), mestrado em Engenharia Elétrica pela Universidade Federal de Itajubá (2009) e doutorado em Engenharia Elétrica pela Universidade Federal de Itajubá (2013). Atualmente é professor adjunto da Universidade Federal de Itajubá. Leciona nas áreas de eletrônica, interface e periféricos, sistemas embarcados e sistemas operacionais. Suas pesquisas incluem tópicos sobre desenvolvimento de hardware, RTOS, segurança e usabilidade de sistemas eletrônicos. Trabalha em projetos de sistemas críticos onde confiabilidade e estabilidade são requisitos, seja do ponto de vista do sistema ou da interação do usuário com o equipamento\nFormação Profissional Acadêmica: Engenheiro de Controle e Automação, Mestrado e Doutorado em Engenharia Eletrica\nÁreas de Interesse: Sistemas embarcados, eletrônica, ensino de engenharia\nÁreas de conhecimento:\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Metodologia e Técnicas da Computação. Especialidade: Sistemas Embarcados\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Sistemas de Computação. Especialidade: Arquitetura de Sistemas de Computação\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Sistemas de Computação. Especialidade: Hardware\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Eletrônica Industrial, Sistemas e Controles Eletrônicos. Especialidade: Controle de Processos Eletrônicos, Retroalimentação\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Medidas Elétricas, Magnéticas e Eletrônicas; Instrumentação. Especialidade: Sistemas Eletrônicos de Medida e de Controle\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Metodologia e Técnicas da Computação. Especialidade: Engenharia de Software\n\nLinhas de pesquisa: Filtros digitais, Desenvolvimento de Firmware, Biosensores e estimuladores elétricos, Sistemas microcontrolados, Sistemas Embarcados, Sistemas Operacionais de Tempo Real, Usabilidade, Desenvolvimento de Firmware, Filtros Digitais, Ensino de Engenharia\n\nPalavras-chave: Sistemas Embarcados, Segurança, Rede neural artificial, Classificação de padrões',
  'score_retrieval': 0.4761905},
 {'professor_id': '1732597',
  'tipo': 'disciplina',
  'item_id': '5651',
  'texto': 'Nome: PROGRAMAÇÃO PARA SISTEMAS EMBARCADOS\nEmenta: conceitos gerais de computação embarcada. programação de sistemas embarcados utilizando linguagem c. tipos de dados e operações com bits. diretivas de compilação e pré-compilação. utilização de periféricos. multiplexação de entradas e saídas. interrupções. organização e arquitetura de programas para sistemas embarcados. limitações de sistemas embarcados.',
  'nome': 'PROGRAMAÇÃO PARA SISTEMAS EMBARCADOS',
  'score_retrieval': 0.75},
 {'professor_id': '1732597',
  'tipo': 'disciplina',
  'item_id': '5300',
  'texto': 'Nome: LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
  'nome': 'LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA',
  'score_retrieval': 0.625},
 {'professor_id': '1732597',
  'tipo': 'disciplina',
  'item_id': '5295',
  'texto': 'Nome: PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
  'nome': 'PROGRAMAÇÃO EMBARCADA',
  'score_retrieval': 0.4761905},
 {'professor_id': '1967206',
  'tipo': 'professor',
  'item_id': '1967206',
  'texto': 'Resumo: Graduou-se em Engenharia Elétrica (1995) pela Universidade Federal de Itajubá (UNIFEI). Concluiu mestrado em Engenharia Elétrica na área de Controle, Automação e Microinformática (1998), pela Universidade Federal de Santa Catarina (UFSC) e doutorado em Computação (2009) pela Universidade Federal Fluminense (UFF), na área de Sistemas Paralelos e Distribuídos. Realizou um ano de pesquisas, em doutorado sanduíche, na Universidade de Pittsburgh, EUA, no laboratório Power-Aware Real-Time Systems. Atuou como engenheiro eletrônico de sistemas embarcados para a empresa Di-elétrons Ltda em Belo Horizonte - MG, de 1999 a 2003. Foi professor de Introdução à Computação e Circuitos Eletro-Eletrônicos na UFRJ, campus de Macaé (temporário 20h nível Adjunto). Foi também engenheiro eletrônico de controle e automação da PETROBRAS em Macaé/RJ entre 2008 e 2014. Tem experiência docente em arquitetura de computadores, circuitos digitais e analógicos, sistemas embarcados, técnicas de programação em C, estruturas de dados e análise de algoritmos. De 2014 a 2022 foi professor Adjunto no Departamento de Computação (RCM) da UFF em Rio das Ostras/RJ, lecionando Circuitos Digitais, Laboratório de Circuitos Digitais e Arquitetura de Computadores. Desde 2022 é professor no Instituto de Engenharia de Sistemas e Tecnologia da informação (IESTI) da UNIFEI na área de sistemas embarcados. Tem interesse em temas de pesquisa relacionados a sistemas embarcados e aplicações com FPGA, Internet das Coisas e controle inteligente de processos industriais\nFormação Profissional Acadêmica: Técnico em eletrônica (1989), engenheiro eletrônico EFEI (1995), mestre em engenharia elétrica UFSC (1998) e doutor em ciência da computação UFF (2009)\nÁreas de Interesse: circuitos digitais, arquitetura de computadores, sistemas embarcados, algoritmos\nÁreas de conhecimento:\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Sistemas de Computação. Especialidade: Arquitetura de Sistemas de Computação\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Circuitos Digitais\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Teoria da Computação. Especialidade: Análise de Algoritmos e Complexidade de Computação\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Sistemas Eficientes Em Energia\n\nLinhas de pesquisa: sistemas embarcados, Internet das Coisas, controle de processos, sistemas digitais\n\nPalavras-chave: Computação Eficiente em Energia, Sistemas de tempo real, Computação Paralela e Distribuída, Clusters de Servidores, Servidores Web, Escalonamento com Otimização da Potência, Sistemas Distribuídos, Sistemas Multimídia Interativos, Padrão CORBA, Padrão MHEG-5, DSMCC e DAVIC',
  'score_retrieval': 0.5},
 {'professor_id': '1967206',
  'tipo': 'disciplina',
  'item_id': '5300',
  'texto': 'Nome: LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
  'nome': 'LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA',
  'score_retrieval': 0.625},
 {'professor_id': '1967206',
  'tipo': 'disciplina',
  'item_id': '5295',
  'texto': 'Nome: PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
  'nome': 'PROGRAMAÇÃO EMBARCADA',
  'score_retrieval': 0.4761905},
 {'professor_id': '1545021',
  'tipo': 'professor',
  'item_id': '1545021',
  'texto': 'Resumo: Possui graduação em Engenharia Elétrica pela Universidade Federal de Itajubá (2001), mestrado em Engenharia Elétrica pela Universidade Federal de Itajubá (2002) e doutorado em Engenharia Elétrica pela Universidade Federal de Itajubá (2006). Atualmente é professor associado 4 da Universidade Federal de Itajubá. Tem experiência na área de Engenharia Elétrica, com ênfase em Automação Eletrônica de Processos Elétricos e Industriais, atuando principalmente nos seguintes temas: inteligência artificial, sistemas elétricos, sistema especialista, controle inteligente e planejamento inteligente\nFormação Profissional Acadêmica: 1996 - Técnico de Eletrônica na ETEFMC; 2001 - Engenheiro Eletricista com Ênfase em Eletrotécnica na EFEI; 2002 - Mestre em Engenharia Elétrica na UNIFEI; 2006 - Doutor em Engenharia Elétrica na UNIFEI.\nÁreas de Interesse: SmartGrid, sistemas embarcados inteligentes, planejamento inteligente, veículos autônomos e engenharia biomédica.\nÁreas de conhecimento:\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Eletrônica Industrial, Sistemas e Controles Eletrônicos. Especialidade: Automação Eletrônica de Processos Elétricos e Industriais\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Computação\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Medidas Elétricas, Magnéticas e Eletrônicas; Instrumentação. Especialidade: Instrumentação Eletrônica\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Eletrônica Industrial, Sistemas e Controles Eletrônicos. Especialidade: Eletrônica Industrial\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Eletrônica Industrial, Sistemas e Controles Eletrônicos. Especialidade: Controle de Processos Eletrônicos, Retroalimentação\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Sistemas Elétricos de Potência. Especialidade: Transmissão da Energia Elétrica, Distribuição da Energia Elétrica\n\nLinhas de pesquisa: Aplicação de Sistemas Inteligentes em Dispositivos Móveis, Aplicação de Sistemas Inteligentes em Sistemas Embarcados, Aplicação de Sistemas Inteligentes na Engenharia de Controle e Automação, Formulação de Modelos Matemáticos para a Engenharia de Controle e Automação, Desenvolvimento e Aplicação de Lógicas Não-Clássicas, Desenvolvimento de Conceitos Teóricos em Inteligência Aritificial, Visão Computacional e Técnicas Avançadas de Reconhecimento de Padrões\n\nPalavras-chave: Agentes Inteligente, Inteligência Artificial, Sistema Elétrico, Mineração de Dados, Transformação da Classe de Tensão, Sistemas Elétricos, Análise Técnico-Econômica',
  'score_retrieval': 0.625},
 {'professor_id': '1545021',
  'tipo': 'disciplina',
  'item_id': '5300',
  'texto': 'Nome: LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
  'nome': 'LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA',
  'score_retrieval': 0.625},
 {'professor_id': '1545021',
  'tipo': 'disciplina',
  'item_id': '5295',
  'texto': 'Nome: PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
  'nome': 'PROGRAMAÇÃO EMBARCADA',
  'score_retrieval': 0.4761905},
 {'professor_id': '1545021',
  'tipo': 'disciplina',
  'item_id': '47044',
  'texto': 'Nome: INTELIGÊNCIA ARTIFICIAL APLICADA\nEmenta: Introdução à Inteligência Artificial Aplicada. Otimizações Evolutivas. Redes Neurais Artificiais. Aprendizado Profundo. Avanços em Inteligência Artificial.',
  'nome': 'INTELIGÊNCIA ARTIFICIAL APLICADA',
  'score_retrieval': 0.11111111},
 {'professor_id': '1374755',
  'tipo': 'professor',
  'item_id': '1374755',
  'texto': 'Resumo: Possui graduação em Engenharia Elétrica pela Universidade Federal de Itajubá (2002), graduação em Matemática Aplicada à Informática (Análise de Sistemas) pela Fundação de Ensino e Pesquisa de Itajubá (1994), Mestrado em Engenharia Elétrica pela Universidade Federal de Itajubá (2016), Doutorado em Engenharia Elétrica pela Universidade Federal de Itajubá (2019). Possui Licenciatura em Eletrônica pela Faculdade Paulista São José (2015) e formação Técnica em Eletrônica pela E. E. Técnico Industrial Tancredo Neves de Brasópolis, MG (1989). Possui experiência em docência no ensino técnico, docência no ensino superior, projetos de circuitos de rádio frequência, projetos de circuitos elétricos e eletrônicos, projeto de antenas e compatibilidade eletromagnética. Atualmente é professor de eletrônica para sistemas embarcados, membro do Grupo de Pesquisa em Telecomunicações (GTELC) e Coordenador do Laboratório de Telecomunicação (LABTEL) na Universidade Federal de Itajubá (UNIFEI)\nFormação Profissional Acadêmica: Técnico em Eletrônica CEP Brazópolis, MG (1989). Análista de Sistemas FEPI Itajubá (1994), Engenharia Elétrica UNIFEI (2002), Mestrado em Microeletrônica UNIFEI (2016), Doutorado em Telecomunicações UNIFEI (2019).\nÁreas de conhecimento:\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Circuitos Elétricos, Magnéticos e Eletrônicos. Especialidade: Circuitos Eletrônicos\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Programação em Sistemas Embarcados\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Sistemas de Telecomunicações\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Teoria Eletromagnetica, Microondas, Propagação de Ondas, Antenas\n\nLinhas de pesquisa: Modulação digital, Transmissão de dados a longas distâncias, Moduladores e amplificadores de RF, Microcontroladores e sistemas embarcados, Cibersegurança\n\nPalavras-chave: Telefonia móvel celular, Eletrônica Analógica, Internet of Things, redes de sensores sem fio, conversor tensão frequência, Modulação PIM',
  'score_retrieval': 0.35},
 {'professor_id': '1374755',
  'tipo': 'disciplina',
  'item_id': '5300',
  'texto': 'Nome: LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
  'nome': 'LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA',
  'score_retrieval': 0.625},
 {'professor_id': '1374755',
  'tipo': 'disciplina',
  'item_id': '5295',
  'texto': 'Nome: PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
  'nome': 'PROGRAMAÇÃO EMBARCADA',
  'score_retrieval': 0.4761905},
 {'professor_id': '1634986',
  'tipo': 'professor',
  'item_id': '1634986',
  'texto': 'Resumo: Atualmente é professor adjunto da Universidade Federal de Itajubá. Doutor em Ciências da Computação e Matemática Computacional pela Universidade de São Paulo. Possui mestrado em Ciências da Computação e Matemática Computacional pela Universidade de São Paulo (2013) e graduação em Ciência da Computação pela Pontifícia Universidade Católica de Minas Gerais (2010). Atua na área de Sistemas Distribuídos, com ênfase em Gateways Científicos, Arquiteturas Orientadas a Serviço (SOA), Workflows Científicos. Colabora pesquisas em Ciência de Dados. Vinculado aos laboratórios Grupo de Pesquisa em Engenharia de Sistemas e Computação (GPESC) e Grupo de Pesquisa em Telecomunicações (GTELC) da UNIFEI\nFormação Profissional Acadêmica: Doutor em Ciências da Computação e Matemática Computacional pela Universidade de São Paulo.\nÁreas de Interesse: Sistemas Distribuídos, Workflows Científicos, e-Science, SOA\nPalavras-chave: Arquitetura Orientada a Serviço, Gateway Científico, Scientific Workflow, Predição de Estruturas de Proteínas, E-Science, Qualidade de Serviço, Tolerância a Falhas, Web Services, Balanceamento de Carga',
  'score_retrieval': 0.07796102},
 {'professor_id': '1634986',
  'tipo': 'trabalho',
  'item_id': '6d9b570e8513',

In [500]:
pares = [
    [aluno_texto, candidato["texto"]]
    for candidato in conteudo_reranking
]

In [501]:
scores = reranker.compute_score(
    pares,
    normalize=True
)

In [502]:
for candidato, score in zip(conteudo_reranking, scores):

    candidato["rerank_score"] = float(score)

In [504]:
from collections import defaultdict

def agrupar_por_professor(candidatos):
    professores = defaultdict(lambda: {
        "professor_id": None,
        "professor": None,
        "trabalhos_relevantes": [],
        "disciplinas_relevantes": []
    })

    for candidato in candidatos:
        professor_id = candidato["professor_id"]

        professores[professor_id]["professor_id"] = professor_id

        if candidato["tipo"] == "professor":
            professores[professor_id]["professor"] = candidato

        elif candidato["tipo"] == "trabalho":
            professores[professor_id]["trabalhos_relevantes"].append(candidato)

        elif candidato["tipo"] == "disciplina":
            professores[professor_id]["disciplinas_relevantes"].append(candidato)

    return dict(professores)

In [510]:
professores_ranked_agrupados = agrupar_por_professor(conteudo_reranking)

In [524]:
def calcular_score_final_professor(dados):
    componentes = []

    if dados["professor_rerank_score"] is not None:
        componentes.append(
            (0.20, dados["professor_rerank_score"])
        )

    if dados["work_rerank_score"] is not None:
        componentes.append(
            (0.50, dados["work_rerank_score"])
        )

    if dados["disciplina_rerank_score"] is not None:
        componentes.append(
            (0.30, dados["disciplina_rerank_score"])
        )

    if not componentes:
        return 0.0

    soma_pesos = sum(
        peso for peso, score in componentes
    )

    soma_scores = sum(
        peso * score
        for peso, score in componentes
    )

    return soma_scores / soma_pesos

In [525]:
def calcular_score_ponderado(itens, n=3):
    if not itens:
        return None

    itens_ordenados = sorted(
        itens,
        key=lambda x: x["rerank_score"],
        reverse=True
    )[:n]

    pesos = list(range(len(itens_ordenados), 0, -1))

    numerador = sum(
        item["rerank_score"] * peso
        for item, peso in zip(itens_ordenados, pesos)
    )

    denominador = sum(pesos)

    return numerador / denominador

In [526]:
def calcular_scores_professor(professores):
    for professor_id, dados in professores.items():

        # Score do perfil do professor
        if dados["professor"] is not None:
            dados["professor_rerank_score"] = (
                dados["professor"]["rerank_score"]
            )
        else:
            dados["professor_rerank_score"] = None

        # Score dos trabalhos
        dados["work_rerank_score"] = calcular_score_ponderado(
            dados["trabalhos_relevantes"],
            n=3
        )

        # Score das disciplinas
        dados["disciplina_rerank_score"] = calcular_score_ponderado(
            dados["disciplinas_relevantes"],
            n=3
        )

    return professores

In [536]:
professores_ranked_agrupados

{'1732597': {'professor_id': '1732597',
  'professor': {'professor_id': '1732597',
   'tipo': 'professor',
   'item_id': '1732597',
   'texto': 'Resumo: Possui graduação em Engenharia de Controle e Automação pela Universidade Federal de Itajubá (2007), mestrado em Engenharia Elétrica pela Universidade Federal de Itajubá (2009) e doutorado em Engenharia Elétrica pela Universidade Federal de Itajubá (2013). Atualmente é professor adjunto da Universidade Federal de Itajubá. Leciona nas áreas de eletrônica, interface e periféricos, sistemas embarcados e sistemas operacionais. Suas pesquisas incluem tópicos sobre desenvolvimento de hardware, RTOS, segurança e usabilidade de sistemas eletrônicos. Trabalha em projetos de sistemas críticos onde confiabilidade e estabilidade são requisitos, seja do ponto de vista do sistema ou da interação do usuário com o equipamento\nFormação Profissional Acadêmica: Engenheiro de Controle e Automação, Mestrado e Doutorado em Engenharia Eletrica\nÁreas de Interesse: Sistemas embarcados, eletrônica, ensino de engenharia\nÁreas de conhecimento:\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Metodologia e Técnicas da Computação. Especialidade: Sistemas Embarcados\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Sistemas de Computação. Especialidade: Arquitetura de Sistemas de Computação\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Sistemas de Computação. Especialidade: Hardware\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Eletrônica Industrial, Sistemas e Controles Eletrônicos. Especialidade: Controle de Processos Eletrônicos, Retroalimentação\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Medidas Elétricas, Magnéticas e Eletrônicas; Instrumentação. Especialidade: Sistemas Eletrônicos de Medida e de Controle\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Metodologia e Técnicas da Computação. Especialidade: Engenharia de Software\n\nLinhas de pesquisa: Filtros digitais, Desenvolvimento de Firmware, Biosensores e estimuladores elétricos, Sistemas microcontrolados, Sistemas Embarcados, Sistemas Operacionais de Tempo Real, Usabilidade, Desenvolvimento de Firmware, Filtros Digitais, Ensino de Engenharia\n\nPalavras-chave: Sistemas Embarcados, Segurança, Rede neural artificial, Classificação de padrões',
   'score_retrieval': 0.4761905,
   'rerank_score': 0.00444900478303619},
  'trabalhos_relevantes': [],
  'disciplinas_relevantes': [{'professor_id': '1732597',
    'tipo': 'disciplina',
    'item_id': '5651',
    'texto': 'Nome: PROGRAMAÇÃO PARA SISTEMAS EMBARCADOS\nEmenta: conceitos gerais de computação embarcada. programação de sistemas embarcados utilizando linguagem c. tipos de dados e operações com bits. diretivas de compilação e pré-compilação. utilização de periféricos. multiplexação de entradas e saídas. interrupções. organização e arquitetura de programas para sistemas embarcados. limitações de sistemas embarcados.',
    'nome': 'PROGRAMAÇÃO PARA SISTEMAS EMBARCADOS',
    'score_retrieval': 0.75,
    'rerank_score': 0.06077478976760928},
   {'professor_id': '1732597',
    'tipo': 'disciplina',
    'item_id': '5300',
    'texto': 'Nome: LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
    'nome': 'LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA',
    'score_retrieval': 0.625,
    'rerank_score': 0.05493990265723834},
   {'professor_id': '1732597',
    'tipo': 'disciplina',
    'item_id': '5295',
    'texto': 'Nome: PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
    'nome': 'PROGRAMAÇÃO EMBARCADA',
    'score_retrieval': 0.4761905,
    'rerank_score': 0.10703084963271951}],
  'professor_rerank_score': 0.00444900478303619,
  'work_rerank_score': None,
  'disciplina_rerank_score': 0.08293033851510258,
  'rerank_score': 0.05153780502227602,
  'professor_nome': 'RODRIGO MAXIMIANO ANTUNES DE ALMEIDA'},
 '1967206': {'professor_id': '1967206',
  'professor': {'professor_id': '1967206',
   'tipo': 'professor',
   'item_id': '1967206',
   'texto': 'Resumo: Graduou-se em Engenharia Elétrica (1995) pela Universidade Federal de Itajubá (UNIFEI). Concluiu mestrado em Engenharia Elétrica na área de Controle, Automação e Microinformática (1998), pela Universidade Federal de Santa Catarina (UFSC) e doutorado em Computação (2009) pela Universidade Federal Fluminense (UFF), na área de Sistemas Paralelos e Distribuídos. Realizou um ano de pesquisas, em doutorado sanduíche, na Universidade de Pittsburgh, EUA, no laboratório Power-Aware Real-Time Systems. Atuou como engenheiro eletrônico de sistemas embarcados para a empresa Di-elétrons Ltda em Belo Horizonte - MG, de 1999 a 2003. Foi professor de Introdução à Computação e Circuitos Eletro-Eletrônicos na UFRJ, campus de Macaé (temporário 20h nível Adjunto). Foi também engenheiro eletrônico de controle e automação da PETROBRAS em Macaé/RJ entre 2008 e 2014. Tem experiência docente em arquitetura de computadores, circuitos digitais e analógicos, sistemas embarcados, técnicas de programação em C, estruturas de dados e análise de algoritmos. De 2014 a 2022 foi professor Adjunto no Departamento de Computação (RCM) da UFF em Rio das Ostras/RJ, lecionando Circuitos Digitais, Laboratório de Circuitos Digitais e Arquitetura de Computadores. Desde 2022 é professor no Instituto de Engenharia de Sistemas e Tecnologia da informação (IESTI) da UNIFEI na área de sistemas embarcados. Tem interesse em temas de pesquisa relacionados a sistemas embarcados e aplicações com FPGA, Internet das Coisas e controle inteligente de processos industriais\nFormação Profissional Acadêmica: Técnico em eletrônica (1989), engenheiro eletrônico EFEI (1995), mestre em engenharia elétrica UFSC (1998) e doutor em ciência da computação UFF (2009)\nÁreas de Interesse: circuitos digitais, arquitetura de computadores, sistemas embarcados, algoritmos\nÁreas de conhecimento:\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Sistemas de Computação. Especialidade: Arquitetura de Sistemas de Computação\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Circuitos Digitais\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Teoria da Computação. Especialidade: Análise de Algoritmos e Complexidade de Computação\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Sistemas Eficientes Em Energia\n\nLinhas de pesquisa: sistemas embarcados, Internet das Coisas, controle de processos, sistemas digitais\n\nPalavras-chave: Computação Eficiente em Energia, Sistemas de tempo real, Computação Paralela e Distribuída, Clusters de Servidores, Servidores Web, Escalonamento com Otimização da Potência, Sistemas Distribuídos, Sistemas Multimídia Interativos, Padrão CORBA, Padrão MHEG-5, DSMCC e DAVIC',
   'score_retrieval': 0.5,
   'rerank_score': 0.007376159611232917},
  'trabalhos_relevantes': [],
  'disciplinas_relevantes': [{'professor_id': '1967206',
    'tipo': 'disciplina',
    'item_id': '5300',
    'texto': 'Nome: LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
    'nome': 'LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA',
    'score_retrieval': 0.625,
    'rerank_score': 0.05493990265723834},
   {'professor_id': '1967206',
    'tipo': 'disciplina',
    'item_id': '5295',
    'texto': 'Nome: PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
    'nome': 'PROGRAMAÇÃO EMBARCADA',
    'score_retrieval': 0.4761905,
    'rerank_score': 0.10703084963271951}],
  'professor_rerank_score': 0.007376159611232917,
  'work_rerank_score': None,
  'disciplina_rerank_score': 0.08966720064089245,
  'rerank_score': 0.05675078422902864,
  'professor_nome': 'LUCIANO BERTINI'},
 '1545021': {'professor_id': '1545021',
  'professor': {'professor_id': '1545021',
   'tipo': 'professor',
   'item_id': '1545021',
   'texto': 'Resumo: Possui graduação em Engenharia Elétrica pela Universidade Federal de Itajubá (2001), mestrado em Engenharia Elétrica pela Universidade Federal de Itajubá (2002) e doutorado em Engenharia Elétrica pela Universidade Federal de Itajubá (2006). Atualmente é professor associado 4 da Universidade Federal de Itajubá. Tem experiência na área de Engenharia Elétrica, com ênfase em Automação Eletrônica de Processos Elétricos e Industriais, atuando principalmente nos seguintes temas: inteligência artificial, sistemas elétricos, sistema especialista, controle inteligente e planejamento inteligente\nFormação Profissional Acadêmica: 1996 - Técnico de Eletrônica na ETEFMC; 2001 - Engenheiro Eletricista com Ênfase em Eletrotécnica na EFEI; 2002 - Mestre em Engenharia Elétrica na UNIFEI; 2006 - Doutor em Engenharia Elétrica na UNIFEI.\nÁreas de Interesse: SmartGrid, sistemas embarcados inteligentes, planejamento inteligente, veículos autônomos e engenharia biomédica.\nÁreas de conhecimento:\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Eletrônica Industrial, Sistemas e Controles Eletrônicos. Especialidade: Automação Eletrônica de Processos Elétricos e Industriais\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Computação\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Medidas Elétricas, Magnéticas e Eletrônicas; Instrumentação. Especialidade: Instrumentação Eletrônica\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Eletrônica Industrial, Sistemas e Controles Eletrônicos. Especialidade: Eletrônica Industrial\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Eletrônica Industrial, Sistemas e Controles Eletrônicos. Especialidade: Controle de Processos Eletrônicos, Retroalimentação\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Sistemas Elétricos de Potência. Especialidade: Transmissão da Energia Elétrica, Distribuição da Energia Elétrica\n\nLinhas de pesquisa: Aplicação de Sistemas Inteligentes em Dispositivos Móveis, Aplicação de Sistemas Inteligentes em Sistemas Embarcados, Aplicação de Sistemas Inteligentes na Engenharia de Controle e Automação, Formulação de Modelos Matemáticos para a Engenharia de Controle e Automação, Desenvolvimento e Aplicação de Lógicas Não-Clássicas, Desenvolvimento de Conceitos Teóricos em Inteligência Aritificial, Visão Computacional e Técnicas Avançadas de Reconhecimento de Padrões\n\nPalavras-chave: Agentes Inteligente, Inteligência Artificial, Sistema Elétrico, Mineração de Dados, Transformação da Classe de Tensão, Sistemas Elétricos, Análise Técnico-Econômica',
   'score_retrieval': 0.625,
   'rerank_score': 0.019847287571922154},
  'trabalhos_relevantes': [],
  'disciplinas_relevantes': [{'professor_id': '1545021',
    'tipo': 'disciplina',
    'item_id': '5300',
    'texto': 'Nome: LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
    'nome': 'LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA',
    'score_retrieval': 0.625,
    'rerank_score': 0.05493990265723834},
   {'professor_id': '1545021',
    'tipo': 'disciplina',
    'item_id': '5295',
    'texto': 'Nome: PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
    'nome': 'PROGRAMAÇÃO EMBARCADA',
    'score_retrieval': 0.4761905,
    'rerank_score': 0.10703084963271951},
   {'professor_id': '1545021',
    'tipo': 'disciplina',
    'item_id': '47044',
    'texto': 'Nome: INTELIGÊNCIA ARTIFICIAL APLICADA\nEmenta: Introdução à Inteligência Artificial Aplicada. Otimizações Evolutivas. Redes Neurais Artificiais. Aprendizado Profundo. Avanços em Inteligência Artificial.',
    'nome': 'INTELIGÊNCIA ARTIFICIAL APLICADA',
    'score_retrieval': 0.11111111,
    'rerank_score': 0.004590825061500495}],
  'professor_rerank_score': 0.019847287571922154,
  'work_rerank_score': None,
  'disciplina_rerank_score': 0.07259386321235595,
  'rerank_score': 0.05149523295618243,
  'professor_nome': 'CARLOS HENRIQUE VALERIO DE MORAES'},
 '1374755': {'professor_id': '1374755',
  'professor': {'professor_id': '1374755',
   'tipo': 'professor',
   'item_id': '1374755',
   'texto': 'Resumo: Possui graduação em Engenharia Elétrica pela Universidade Federal de Itajubá (2002), graduação em Matemática Aplicada à Informática (Análise de Sistemas) pela Fundação de Ensino e Pesquisa de Itajubá (1994), Mestrado em Engenharia Elétrica pela Universidade Federal de Itajubá (2016), Doutorado em Engenharia Elétrica pela Universidade Federal de Itajubá (2019). Possui Licenciatura em Eletrônica pela Faculdade Paulista São José (2015) e formação Técnica em Eletrônica pela E. E. Técnico Industrial Tancredo Neves de Brasópolis, MG (1989). Possui experiência em docência no ensino técnico, docência no ensino superior, projetos de circuitos de rádio frequência, projetos de circuitos elétricos e eletrônicos, projeto de antenas e compatibilidade eletromagnética. Atualmente é professor de eletrônica para sistemas embarcados, membro do Grupo de Pesquisa em Telecomunicações (GTELC) e Coordenador do Laboratório de Telecomunicação (LABTEL) na Universidade Federal de Itajubá (UNIFEI)\nFormação Profissional Acadêmica: Técnico em Eletrônica CEP Brazópolis, MG (1989). Análista de Sistemas FEPI Itajubá (1994), Engenharia Elétrica UNIFEI (2002), Mestrado em Microeletrônica UNIFEI (2016), Doutorado em Telecomunicações UNIFEI (2019).\nÁreas de conhecimento:\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Circuitos Elétricos, Magnéticos e Eletrônicos. Especialidade: Circuitos Eletrônicos\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Programação em Sistemas Embarcados\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Sistemas de Telecomunicações\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Teoria Eletromagnetica, Microondas, Propagação de Ondas, Antenas\n\nLinhas de pesquisa: Modulação digital, Transmissão de dados a longas distâncias, Moduladores e amplificadores de RF, Microcontroladores e sistemas embarcados, Cibersegurança\n\nPalavras-chave: Telefonia móvel celular, Eletrônica Analógica, Internet of Things, redes de sensores sem fio, conversor tensão frequência, Modulação PIM',
   'score_retrieval': 0.35,
   'rerank_score': 0.0021035871448503497},
  'trabalhos_relevantes': [],
  'disciplinas_relevantes': [{'professor_id': '1374755',
    'tipo': 'disciplina',
    'item_id': '5300',
    'texto': 'Nome: LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
    'nome': 'LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA',
    'score_retrieval': 0.625,
    'rerank_score': 0.05493990265723834},
   {'professor_id': '1374755',
    'tipo': 'disciplina',
    'item_id': '5295',
    'texto': 'Nome: PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
    'nome': 'PROGRAMAÇÃO EMBARCADA',
    'score_retrieval': 0.4761905,
    'rerank_score': 0.10703084963271951}],
  'professor_rerank_score': 0.0021035871448503497,
  'work_rerank_score': None,
  'disciplina_rerank_score': 0.08966720064089245,
  'rerank_score': 0.05464175524247561,
  'professor_nome': 'DECIO RENNO DE MENDONCA FARIA'},
 '1634986': {'professor_id': '1634986',
  'professor': {'professor_id': '1634986',
   'tipo': 'professor',
   'item_id': '1634986',
   'texto': 'Resumo: Atualmente é professor adjunto da Universidade Federal de Itajubá. Doutor em Ciências da Computação e Matemática Computacional pela Universidade de São Paulo. Possui mestrado em Ciências da Computação e Matemática Computacional pela Universidade de São Paulo (2013) e graduação em Ciência da Computação pela Pontifícia Universidade Católica de Minas Gerais (2010). Atua na área de Sistemas Distribuídos, com ênfase em Gateways Científicos, Arquiteturas Orientadas a Serviço (SOA), Workflows Científicos. Colabora pesquisas em Ciência de Dados. Vinculado aos laboratórios Grupo de Pesquisa em Engenharia de Sistemas e Computação (GPESC) e Grupo de Pesquisa em Telecomunicações (GTELC) da UNIFEI\nFormação Profissional Acadêmica: Doutor em Ciências da Computação e Matemática Computacional pela Universidade de São Paulo.\nÁreas de Interesse: Sistemas Distribuídos, Workflows Científicos, e-Science, SOA\nPalavras-chave: Arquitetura Orientada a Serviço, Gateway Científico, Scientific Workflow, Predição de Estruturas de Proteínas, E-Science, Qualidade de Serviço, Tolerância a Falhas, Web Services, Balanceamento de Carga',
   'score_retrieval': 0.07796102,
   'rerank_score': 5.9985436527396616e-05},
  'trabalhos_relevantes': [{'professor_id': '1634986',
    'tipo': 'trabalho',
    'item_id': '6d9b570e8513',

In [527]:
professores_scores = calcular_scores_professor(
    professores_ranked_agrupados
)

In [528]:
for professor_id, dados in professores_scores.items():

    dados["rerank_score"] = (
        calcular_score_final_professor(dados)
    )

In [529]:
ranking_final = sorted(
    professores_scores.values(),
    key=lambda x: x["rerank_score"],
    reverse=True
)

In [530]:
ranking_final

[{'professor_id': '1967206',
  'professor': {'professor_id': '1967206',
   'tipo': 'professor',
   'item_id': '1967206',
   'texto': 'Resumo: Graduou-se em Engenharia Elétrica (1995) pela Universidade Federal de Itajubá (UNIFEI). Concluiu mestrado em Engenharia Elétrica na área de Controle, Automação e Microinformática (1998), pela Universidade Federal de Santa Catarina (UFSC) e doutorado em Computação (2009) pela Universidade Federal Fluminense (UFF), na área de Sistemas Paralelos e Distribuídos. Realizou um ano de pesquisas, em doutorado sanduíche, na Universidade de Pittsburgh, EUA, no laboratório Power-Aware Real-Time Systems. Atuou como engenheiro eletrônico de sistemas embarcados para a empresa Di-elétrons Ltda em Belo Horizonte - MG, de 1999 a 2003. Foi professor de Introdução à Computação e Circuitos Eletro-Eletrônicos na UFRJ, campus de Macaé (temporário 20h nível Adjunto). Foi também engenheiro eletrônico de controle e automação da PETROBRAS em Macaé/RJ entre 2008 e 2014. Tem experiência docente em arquitetura de computadores, circuitos digitais e analógicos, sistemas embarcados, técnicas de programação em C, estruturas de dados e análise de algoritmos. De 2014 a 2022 foi professor Adjunto no Departamento de Computação (RCM) da UFF em Rio das Ostras/RJ, lecionando Circuitos Digitais, Laboratório de Circuitos Digitais e Arquitetura de Computadores. Desde 2022 é professor no Instituto de Engenharia de Sistemas e Tecnologia da informação (IESTI) da UNIFEI na área de sistemas embarcados. Tem interesse em temas de pesquisa relacionados a sistemas embarcados e aplicações com FPGA, Internet das Coisas e controle inteligente de processos industriais\nFormação Profissional Acadêmica: Técnico em eletrônica (1989), engenheiro eletrônico EFEI (1995), mestre em engenharia elétrica UFSC (1998) e doutor em ciência da computação UFF (2009)\nÁreas de Interesse: circuitos digitais, arquitetura de computadores, sistemas embarcados, algoritmos\nÁreas de conhecimento:\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Sistemas de Computação. Especialidade: Arquitetura de Sistemas de Computação\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Circuitos Digitais\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Teoria da Computação. Especialidade: Análise de Algoritmos e Complexidade de Computação\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Sistemas Eficientes Em Energia\n\nLinhas de pesquisa: sistemas embarcados, Internet das Coisas, controle de processos, sistemas digitais\n\nPalavras-chave: Computação Eficiente em Energia, Sistemas de tempo real, Computação Paralela e Distribuída, Clusters de Servidores, Servidores Web, Escalonamento com Otimização da Potência, Sistemas Distribuídos, Sistemas Multimídia Interativos, Padrão CORBA, Padrão MHEG-5, DSMCC e DAVIC',
   'score_retrieval': 0.5,
   'rerank_score': 0.007376159611232917},
  'trabalhos_relevantes': [],
  'disciplinas_relevantes': [{'professor_id': '1967206',
    'tipo': 'disciplina',
    'item_id': '5300',
    'texto': 'Nome: LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
    'nome': 'LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA',
    'score_retrieval': 0.625,
    'rerank_score': 0.05493990265723834},
   {'professor_id': '1967206',
    'tipo': 'disciplina',
    'item_id': '5295',
    'texto': 'Nome: PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
    'nome': 'PROGRAMAÇÃO EMBARCADA',
    'score_retrieval': 0.4761905,
    'rerank_score': 0.10703084963271951}],
  'professor_rerank_score': 0.007376159611232917,
  'work_rerank_score': None,
  'disciplina_rerank_score': 0.08966720064089245,
  'rerank_score': 0.05675078422902864,
  'professor_nome': 'LUCIANO BERTINI'},
 {'professor_id': '1374755',
  'professor': {'professor_id': '1374755',
   'tipo': 'professor',
   'item_id': '1374755',
   'texto': 'Resumo: Possui graduação em Engenharia Elétrica pela Universidade Federal de Itajubá (2002), graduação em Matemática Aplicada à Informática (Análise de Sistemas) pela Fundação de Ensino e Pesquisa de Itajubá (1994), Mestrado em Engenharia Elétrica pela Universidade Federal de Itajubá (2016), Doutorado em Engenharia Elétrica pela Universidade Federal de Itajubá (2019). Possui Licenciatura em Eletrônica pela Faculdade Paulista São José (2015) e formação Técnica em Eletrônica pela E. E. Técnico Industrial Tancredo Neves de Brasópolis, MG (1989). Possui experiência em docência no ensino técnico, docência no ensino superior, projetos de circuitos de rádio frequência, projetos de circuitos elétricos e eletrônicos, projeto de antenas e compatibilidade eletromagnética. Atualmente é professor de eletrônica para sistemas embarcados, membro do Grupo de Pesquisa em Telecomunicações (GTELC) e Coordenador do Laboratório de Telecomunicação (LABTEL) na Universidade Federal de Itajubá (UNIFEI)\nFormação Profissional Acadêmica: Técnico em Eletrônica CEP Brazópolis, MG (1989). Análista de Sistemas FEPI Itajubá (1994), Engenharia Elétrica UNIFEI (2002), Mestrado em Microeletrônica UNIFEI (2016), Doutorado em Telecomunicações UNIFEI (2019).\nÁreas de conhecimento:\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Circuitos Elétricos, Magnéticos e Eletrônicos. Especialidade: Circuitos Eletrônicos\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Programação em Sistemas Embarcados\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Sistemas de Telecomunicações\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Teoria Eletromagnetica, Microondas, Propagação de Ondas, Antenas\n\nLinhas de pesquisa: Modulação digital, Transmissão de dados a longas distâncias, Moduladores e amplificadores de RF, Microcontroladores e sistemas embarcados, Cibersegurança\n\nPalavras-chave: Telefonia móvel celular, Eletrônica Analógica, Internet of Things, redes de sensores sem fio, conversor tensão frequência, Modulação PIM',
   'score_retrieval': 0.35,
   'rerank_score': 0.0021035871448503497},
  'trabalhos_relevantes': [],
  'disciplinas_relevantes': [{'professor_id': '1374755',
    'tipo': 'disciplina',
    'item_id': '5300',
    'texto': 'Nome: LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
    'nome': 'LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA',
    'score_retrieval': 0.625,
    'rerank_score': 0.05493990265723834},
   {'professor_id': '1374755',
    'tipo': 'disciplina',
    'item_id': '5295',
    'texto': 'Nome: PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
    'nome': 'PROGRAMAÇÃO EMBARCADA',
    'score_retrieval': 0.4761905,
    'rerank_score': 0.10703084963271951}],
  'professor_rerank_score': 0.0021035871448503497,
  'work_rerank_score': None,
  'disciplina_rerank_score': 0.08966720064089245,
  'rerank_score': 0.05464175524247561,
  'professor_nome': 'DECIO RENNO DE MENDONCA FARIA'},
 {'professor_id': '1732597',
  'professor': {'professor_id': '1732597',
   'tipo': 'professor',
   'item_id': '1732597',
   'texto': 'Resumo: Possui graduação em Engenharia de Controle e Automação pela Universidade Federal de Itajubá (2007), mestrado em Engenharia Elétrica pela Universidade Federal de Itajubá (2009) e doutorado em Engenharia Elétrica pela Universidade Federal de Itajubá (2013). Atualmente é professor adjunto da Universidade Federal de Itajubá. Leciona nas áreas de eletrônica, interface e periféricos, sistemas embarcados e sistemas operacionais. Suas pesquisas incluem tópicos sobre desenvolvimento de hardware, RTOS, segurança e usabilidade de sistemas eletrônicos. Trabalha em projetos de sistemas críticos onde confiabilidade e estabilidade são requisitos, seja do ponto de vista do sistema ou da interação do usuário com o equipamento\nFormação Profissional Acadêmica: Engenheiro de Controle e Automação, Mestrado e Doutorado em Engenharia Eletrica\nÁreas de Interesse: Sistemas embarcados, eletrônica, ensino de engenharia\nÁreas de conhecimento:\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Metodologia e Técnicas da Computação. Especialidade: Sistemas Embarcados\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Sistemas de Computação. Especialidade: Arquitetura de Sistemas de Computação\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Sistemas de Computação. Especialidade: Hardware\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Eletrônica Industrial, Sistemas e Controles Eletrônicos. Especialidade: Controle de Processos Eletrônicos, Retroalimentação\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Medidas Elétricas, Magnéticas e Eletrônicas; Instrumentação. Especialidade: Sistemas Eletrônicos de Medida e de Controle\nGrande área: Ciências Exatas e da Terra. Área: Ciência da Computação. Subárea: Metodologia e Técnicas da Computação. Especialidade: Engenharia de Software\n\nLinhas de pesquisa: Filtros digitais, Desenvolvimento de Firmware, Biosensores e estimuladores elétricos, Sistemas microcontrolados, Sistemas Embarcados, Sistemas Operacionais de Tempo Real, Usabilidade, Desenvolvimento de Firmware, Filtros Digitais, Ensino de Engenharia\n\nPalavras-chave: Sistemas Embarcados, Segurança, Rede neural artificial, Classificação de padrões',
   'score_retrieval': 0.4761905,
   'rerank_score': 0.00444900478303619},
  'trabalhos_relevantes': [],
  'disciplinas_relevantes': [{'professor_id': '1732597',
    'tipo': 'disciplina',
    'item_id': '5651',
    'texto': 'Nome: PROGRAMAÇÃO PARA SISTEMAS EMBARCADOS\nEmenta: conceitos gerais de computação embarcada. programação de sistemas embarcados utilizando linguagem c. tipos de dados e operações com bits. diretivas de compilação e pré-compilação. utilização de periféricos. multiplexação de entradas e saídas. interrupções. organização e arquitetura de programas para sistemas embarcados. limitações de sistemas embarcados.',
    'nome': 'PROGRAMAÇÃO PARA SISTEMAS EMBARCADOS',
    'score_retrieval': 0.75,
    'rerank_score': 0.06077478976760928},
   {'professor_id': '1732597',
    'tipo': 'disciplina',
    'item_id': '5300',
    'texto': 'Nome: LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
    'nome': 'LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA',
    'score_retrieval': 0.625,
    'rerank_score': 0.05493990265723834},
   {'professor_id': '1732597',
    'tipo': 'disciplina',
    'item_id': '5295',
    'texto': 'Nome: PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
    'nome': 'PROGRAMAÇÃO EMBARCADA',
    'score_retrieval': 0.4761905,
    'rerank_score': 0.10703084963271951}],
  'professor_rerank_score': 0.00444900478303619,
  'work_rerank_score': None,
  'disciplina_rerank_score': 0.08293033851510258,
  'rerank_score': 0.05153780502227602,
  'professor_nome': 'RODRIGO MAXIMIANO ANTUNES DE ALMEIDA'},
 {'professor_id': '1545021',
  'professor': {'professor_id': '1545021',
   'tipo': 'professor',
   'item_id': '1545021',
   'texto': 'Resumo: Possui graduação em Engenharia Elétrica pela Universidade Federal de Itajubá (2001), mestrado em Engenharia Elétrica pela Universidade Federal de Itajubá (2002) e doutorado em Engenharia Elétrica pela Universidade Federal de Itajubá (2006). Atualmente é professor associado 4 da Universidade Federal de Itajubá. Tem experiência na área de Engenharia Elétrica, com ênfase em Automação Eletrônica de Processos Elétricos e Industriais, atuando principalmente nos seguintes temas: inteligência artificial, sistemas elétricos, sistema especialista, controle inteligente e planejamento inteligente\nFormação Profissional Acadêmica: 1996 - Técnico de Eletrônica na ETEFMC; 2001 - Engenheiro Eletricista com Ênfase em Eletrotécnica na EFEI; 2002 - Mestre em Engenharia Elétrica na UNIFEI; 2006 - Doutor em Engenharia Elétrica na UNIFEI.\nÁreas de Interesse: SmartGrid, sistemas embarcados inteligentes, planejamento inteligente, veículos autônomos e engenharia biomédica.\nÁreas de conhecimento:\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Eletrônica Industrial, Sistemas e Controles Eletrônicos. Especialidade: Automação Eletrônica de Processos Elétricos e Industriais\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Computação\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Medidas Elétricas, Magnéticas e Eletrônicas; Instrumentação. Especialidade: Instrumentação Eletrônica\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Eletrônica Industrial, Sistemas e Controles Eletrônicos. Especialidade: Eletrônica Industrial\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Eletrônica Industrial, Sistemas e Controles Eletrônicos. Especialidade: Controle de Processos Eletrônicos, Retroalimentação\nGrande área: Engenharias. Área: Engenharia Elétrica. Subárea: Sistemas Elétricos de Potência. Especialidade: Transmissão da Energia Elétrica, Distribuição da Energia Elétrica\n\nLinhas de pesquisa: Aplicação de Sistemas Inteligentes em Dispositivos Móveis, Aplicação de Sistemas Inteligentes em Sistemas Embarcados, Aplicação de Sistemas Inteligentes na Engenharia de Controle e Automação, Formulação de Modelos Matemáticos para a Engenharia de Controle e Automação, Desenvolvimento e Aplicação de Lógicas Não-Clássicas, Desenvolvimento de Conceitos Teóricos em Inteligência Aritificial, Visão Computacional e Técnicas Avançadas de Reconhecimento de Padrões\n\nPalavras-chave: Agentes Inteligente, Inteligência Artificial, Sistema Elétrico, Mineração de Dados, Transformação da Classe de Tensão, Sistemas Elétricos, Análise Técnico-Econômica',
   'score_retrieval': 0.625,
   'rerank_score': 0.019847287571922154},
  'trabalhos_relevantes': [],
  'disciplinas_relevantes': [{'professor_id': '1545021',
    'tipo': 'disciplina',
    'item_id': '5300',
    'texto': 'Nome: LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
    'nome': 'LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA',
    'score_retrieval': 0.625,
    'rerank_score': 0.05493990265723834},
   {'professor_id': '1545021',
    'tipo': 'disciplina',
    'item_id': '5295',
    'texto': 'Nome: PROGRAMAÇÃO EMBARCADA\nEmenta: Conceitos gerais de computação embarcada. Programação de sistemas embarcados utilizando linguagem C. Tipos de dados e operações com bits. Diretivas de compilação e pré-compilação. Utilização de periféricos: entradas e saídas digitais, DAC, PWM, Serial RS232, timers e watchdog. Multiplexação de entradas e saídas (displays e teclado). Interrupções. Organização e arquitetura de programas para sistemas embarcados. Limitações de sistemas embarcados.',
    'nome': 'PROGRAMAÇÃO EMBARCADA',
    'score_retrieval': 0.4761905,
    'rerank_score': 0.10703084963271951},
   {'professor_id': '1545021',
    'tipo': 'disciplina',
    'item_id': '47044',
    'texto': 'Nome: INTELIGÊNCIA ARTIFICIAL APLICADA\nEmenta: Introdução à Inteligência Artificial Aplicada. Otimizações Evolutivas. Redes Neurais Artificiais. Aprendizado Profundo. Avanços em Inteligência Artificial.',
    'nome': 'INTELIGÊNCIA ARTIFICIAL APLICADA',
    'score_retrieval': 0.11111111,
    'rerank_score': 0.004590825061500495}],
  'professor_rerank_score': 0.019847287571922154,
  'work_rerank_score': None,
  'disciplina_rerank_score': 0.07259386321235595,
  'rerank_score': 0.05149523295618243,
  'professor_nome': 'CARLOS HENRIQUE VALERIO DE MORAES'},
 {'professor_id': '1634986',
  'professor': {'professor_id': '1634986',
   'tipo': 'professor',
   'item_id': '1634986',
   'texto': 'Resumo: Atualmente é professor adjunto da Universidade Federal de Itajubá. Doutor em Ciências da Computação e Matemática Computacional pela Universidade de São Paulo. Possui mestrado em Ciências da Computação e Matemática Computacional pela Universidade de São Paulo (2013) e graduação em Ciência da Computação pela Pontifícia Universidade Católica de Minas Gerais (2010). Atua na área de Sistemas Distribuídos, com ênfase em Gateways Científicos, Arquiteturas Orientadas a Serviço (SOA), Workflows Científicos. Colabora pesquisas em Ciência de Dados. Vinculado aos laboratórios Grupo de Pesquisa em Engenharia de Sistemas e Computação (GPESC) e Grupo de Pesquisa em Telecomunicações (GTELC) da UNIFEI\nFormação Profissional Acadêmica: Doutor em Ciências da Computação e Matemática Computacional pela Universidade de São Paulo.\nÁreas de Interesse: Sistemas Distribuídos, Workflows Científicos, e-Science, SOA\nPalavras-chave: Arquitetura Orientada a Serviço, Gateway Científico, Scientific Workflow, Predição de Estruturas de Proteínas, E-Science, Qualidade de Serviço, Tolerância a Falhas, Web Services, Balanceamento de Carga',
   'score_retrieval': 0.07796102,
   'rerank_score': 5.9985436527396616e-05},
  'trabalhos_relevantes': [{'professor_id': '1634986',
    'tipo': 'trabalho',
    'item_id': '6d9b570e8513',

In [531]:
def adicionar_nomes_professores(ranking_final, ranking):
    nomes = (
        ranking[
            ["professor_id", "professor_nome"]
        ]
        .drop_duplicates("professor_id")
        .set_index("professor_id")["professor_nome"]
        .to_dict()
    )

    for professor in ranking_final:
        professor["professor_nome"] = nomes.get(
            professor["professor_id"],
            professor["professor_id"]
        )

    return ranking_final

In [532]:
ranking_final = adicionar_nomes_professores(ranking_final,score_final_professores)

In [534]:
def imprimir_ranking(ranking_final, aluno_texto):

    print("CONSULTA DO ALUNO")
    print(aluno_texto)

    print("\n" + "=" * 100)
    print("RANKING COMPLETO")
    print("=" * 100)

    for i, professor in enumerate(ranking_final, start=1):

        print("=" * 100)

        print(
            f"{i}º - {professor['professor_nome']}"
        )

        print(
            f"Rerank score: "
            f"{professor['rerank_score']:.6f}"
        )

        print(
            f"Score inicial: "
            f"{professor['professor']['score_retrieval']:.6f}"
            if professor["professor"] is not None
            else "Score inicial: N/A"
        )

        # ==================================================
        # TRABALHOS
        # ==================================================

        print("\nTrabalhos relevantes:")

        trabalhos = professor["trabalhos_relevantes"]

        if not trabalhos:
            print("Nenhum trabalho relevante encontrado.")
        else:
            trabalhos = sorted(
                trabalhos,
                key=lambda x: x["rerank_score"],
                reverse=True
            )

            for j, trabalho in enumerate(trabalhos, start=1):

                titulo = trabalho.get("titulo")

                if not titulo:
                    titulo = trabalho["texto"].split("\n")[0]

                    if titulo.startswith("Título:"):
                        titulo = titulo.replace(
                            "Título:", "", 1
                        ).strip()

                print(f"\n  {j}. {titulo}")

                print(
                    f"     Score do trabalho: "
                    f"{trabalho['rerank_score']:.6f}"
                )

        # ==================================================
        # DISCIPLINAS
        # ==================================================

        print("\nDisciplinas relevantes:")

        disciplinas = professor["disciplinas_relevantes"]

        if not disciplinas:
            print("Nenhuma disciplina relevante encontrada.")
        else:
            disciplinas = sorted(
                disciplinas,
                key=lambda x: x["rerank_score"],
                reverse=True
            )

            for j, disciplina in enumerate(disciplinas, start=1):

                nome = disciplina.get("nome")

                if not nome:
                    nome = disciplina["texto"].split("\n")[0]

                    if nome.startswith("Nome:"):
                        nome = nome.replace(
                            "Nome:", "", 1
                        ).strip()

                print(f"\n  {j}. {nome}")

                print(
                    f"     Score da disciplina: "
                    f"{disciplina['rerank_score']:.6f}"
                )

In [535]:
imprimir_ranking(ranking_final[:10],aluno_texto)

CONSULTA DO ALUNO
Gostaria de desenvolver um projeto com inteligência artificial e programação embarcada

====================================================================================================
RANKING COMPLETO
====================================================================================================
====================================================================================================
1º - LUCIANO BERTINI
Rerank score: 0.056751
Score inicial: 0.500000

Trabalhos relevantes:
Nenhum trabalho relevante encontrado.

Disciplinas relevantes:

  1. PROGRAMAÇÃO EMBARCADA
     Score da disciplina: 0.107031

  2. LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA
     Score da disciplina: 0.054940
====================================================================================================
2º - DECIO RENNO DE MENDONCA FARIA
Rerank score: 0.054642
Score inicial: 0.350000

Trabalhos relevantes:
Nenhum trabalho relevante encontrado.

Disciplinas relevantes:

  1. PROGRAMAÇÃO EMBARCADA
     Score da disciplina: 0.107031

  2. LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA
     Score da disciplina: 0.054940
====================================================================================================
3º - RODRIGO MAXIMIANO ANTUNES DE ALMEIDA
Rerank score: 0.051538
Score inicial: 0.476191

Trabalhos relevantes:
Nenhum trabalho relevante encontrado.

Disciplinas relevantes:

  1. PROGRAMAÇÃO EMBARCADA
     Score da disciplina: 0.107031

  2. PROGRAMAÇÃO PARA SISTEMAS EMBARCADOS
     Score da disciplina: 0.060775

  3. LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA
     Score da disciplina: 0.054940
====================================================================================================
4º - CARLOS HENRIQUE VALERIO DE MORAES
Rerank score: 0.051495
Score inicial: 0.625000

Trabalhos relevantes:
Nenhum trabalho relevante encontrado.

Disciplinas relevantes:

  1. PROGRAMAÇÃO EMBARCADA
     Score da disciplina: 0.107031

  2. LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA
     Score da disciplina: 0.054940

  3. INTELIGÊNCIA ARTIFICIAL APLICADA
     Score da disciplina: 0.004591
====================================================================================================
5º - EDVARD MARTINS DE OLIVEIRA
Rerank score: 0.046259
Score inicial: 0.077961

Trabalhos relevantes:

  1. ESTUDO DE SISTEMAS EMBARCADOS NA AGRICULTURA DIGITAL
     Score do trabalho: 0.092294

Disciplinas relevantes:

  1. LABORATÓRIO DE TÉCNICAS DE PROGRAMAÇÃO
     Score da disciplina: 0.000332
====================================================================================================
6º - JOSE ALBERTO FERREIRA FILHO
Rerank score: 0.038246
Score inicial: 0.238095

Trabalhos relevantes:
Nenhum trabalho relevante encontrado.

Disciplinas relevantes:

  1. TINYML - APRENDIZADO DE MÁQUINA APLICADO PARA DISPOSITIVOS IOT EMBARCADOS
     Score da disciplina: 0.123726

  2. APRENDIZADO BASEADO EM PROJETO I
     Score da disciplina: 0.000558

  3. ORGANIZAÇÃO INDUSTRIAL E MANUFATURA DE PRODUTOS ELETRÔNICOS
     Score da disciplina: 0.000208
====================================================================================================
7º - GABRIEL CIRAC MENDES DE SOUZA
Rerank score: 0.036737
Score inicial: N/A

Trabalhos relevantes:
Nenhum trabalho relevante encontrado.

Disciplinas relevantes:

  1. LABORATÓRIO DE PROGRAMAÇÃO EMBARCADA
     Score da disciplina: 0.054940

  2. LABORATÓRIO DE TÉCNICAS DE PROGRAMAÇÃO
     Score da disciplina: 0.000332
====================================================================================================
8º - LUIS HENRIQUE DE CARVALHO FERREIRA
Rerank score: 0.016229
Score inicial: 0.098824

Trabalhos relevantes:
Nenhum trabalho relevante encontrado.

Disciplinas relevantes:

  1. APRENDIZADO BASEADO EM PROJETO III
     Score da disciplina: 0.027013
====================================================================================================
9º - ROBSON BAUWELZ GONZATTI
Rerank score: 0.009299
Score inicial: 0.067873

Trabalhos relevantes:

  1. APLICAÇÃO DE TÉCNICAS DE INTELIGÊNCIA ARTIFICIAL PARA CONTROLE DE CONVERSOR DC-DC
     Score do trabalho: 0.019103

  2. DESENVOLVIMENTO DE UMA PLATAFORMA BASEADA EM SISTEMA OPERACIONAL EM TEMPO REAL PARA UM MÓDULO DE GERENCIAMENTO ENERGÉTICO
     Score do trabalho: 0.000816

Disciplinas relevantes:
Nenhuma disciplina relevante encontrada.
====================================================================================================
10º - GUSTAVO DELLA COLLETTA
Rerank score: 0.004195
Score inicial: 0.049451

Trabalhos relevantes:

  1. Estudo e desenvolvimento de uma microarquitetura RISC-V baseado no ISA RV32I.
     Score do trabalho: 0.012316

  2. Estudo e desenvolvimento de periféricos internos para trabalhar em conjunto com microarquiteturas RISC-V baseadas no ISA RV32I.
     Score do trabalho: 0.000235

Disciplinas relevantes:

  1. MICROCONTROLADORES (PRÁTICA)
     Score da disciplina: 0.000148